# Logging Results

In [2]:
def log_top_matches(query, model_name, top_indices, similarities, full_psalms, filename="query_results.txt"):
    """
    Write the top psalm matches to a results file (and print them).
    Includes the original query and model information as a heading.
    """
    output_lines = []
    output_lines.append("=" * 80)
    output_lines.append(f"Query: {query}")
    output_lines.append(f"Model: {model_name}")
    output_lines.append("Top 5 matching psalms:")

    line_length = 125

    for rank, idx in enumerate(top_indices, start=1):
        text_type = "Bible" if idx <= 151 else "Psalter"
        num = idx if idx <= 151 else idx - 151
        psalm = full_psalms.iloc[idx]['verse']
        formatted_verse = ""
        # split into lines of length `line_length`
        for i in range(0, len(text), line_length):
            formatted_verse += psalm[i:i+line_length] + "\n"

        line = (
            f"{rank}. {text_type} Psalm {num + 1} - Similarity: {similarities[idx]}%\n"
            f"{formatted_verse}\n"
        )
        output_lines.append(line)

    # Combine into one result block
    result_block = "\n".join(output_lines)

    # Print to console
    print(result_block)

    # Append to a file
    with open(filename, "a", encoding="utf-8") as f:
        f.write(result_block + "\n\n")

%pip install --upgrade \
  torch \
  transformers \
  sentence-transformers \
  datasets \
  huggingface_hub \
  pyarrow

# GLoVe X TFIDF

In [3]:
import pandas as pd
import numpy as np

psalms = pd.read_csv("../data/psalms_with_vectors.csv")

/opt/conda/lib/python3.11/site-packages/pandas/core/computation/expressions.py:22: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.8.4' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
/opt/conda/lib/python3.11/site-packages/pandas/core/arrays/masked.py:56: UserWarning: Pandas requires version '1.4.2' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [4]:
import pandas as pd
import numpy as np

df = pd.read_csv("../data/psalms_with_vectors.csv")

df["glove_vec"] = df["glove"].apply(
    lambda x: np.fromstring(
        str(x).replace("[", "").replace("]", ""),
        sep=" "
     )
)

In [5]:
df

,Unnamed: 0,tradition,text,psalm_num,verse,cleaned_verse,glove_tfidf_vec,glove,glove_vec
0,0,Orthodox,Bible,1,Blessed is the man Who walks not in the counse...,blessed man walk counsel ungodly stand way sin...,[ 0.04116335 -0.16281123 0.01578085 0.102900...,[-0.01810831 -0.2523851 0.00547219 0.195684...,"[-0.01810831, -0.2523851, 0.00547219, 0.195684..."
1,1,Orthodox,Bible,2,Why do the nations rage And the people meditat...,nation rage people meditate vain thing king ea...,[-0.09802769 -0.09030678 0.08969123 0.121389...,[-0.13752478 -0.16025928 0.08164851 0.207276...,"[-0.13752478, -0.16025928, 0.08164851, 0.20727..."
2,2,Orthodox,Bible,3,A psalm by David when he fled from the face of...,psalm david fled face son absalom olord afflic...,[-0.02370331 -0.02989303 -0.06902936 0.134278...,[-0.06051026 -0.02464193 -0.06952135 0.176681...,"[-0.06051026, -0.02464193, -0.06952135, 0.1766..."
3,3,Orthodox,Bible,4,For the End in psalms an ode by David You hear...,end psalm ode david heard icalled god righteou...,[-0.04905575 -0.02581999 -0.03994774 0.128105...,[-0.08449795 -0.0195749 0.00881046 0.162734...,"[-0.08449795, -0.0195749, 0.00881046, 0.162734..."
4,4,Orthodox,Bible,5,For the End concerning the inheritance a psalm...,end concerning inheritance psalm david give ea...,[ 0.00102828 -0.09200042 -0.07703259 0.243362...,[-0.0342767 -0.13337569 -0.09014621 0.313558...,"[-0.0342767, -0.13337569, -0.09014621, 0.31355..."
...,...,...,...,...,...,...,...,...,...
296,296,Orthodox,Psalter,146,The Lord doth build up Jerusalem; He shall gat...,lord doth build jerusalem ; shall gather toget...,[-8.69649883e-02 2.96077896e-02 2.16656047e-...,[-0.00202334 -0.09045612 0.07749773 0.364389...,"[-0.00202334, -0.09045612, 0.07749773, 0.36438..."
297,297,Orthodox,Psalter,147,"Praise the Lord, O Jerusalem; praise thy God, ...","praise lord , jerusalem ; praise thy god , zio...",[-0.07291189 -0.04181115 0.07198007 0.143565...,[-0.00506784 -0.17236896 0.10899492 0.362852...,"[-0.00506784, -0.17236896, 0.10899492, 0.36285..."
298,298,Orthodox,Psalter,148,Praise ye the Lord from the heavens; praise Hi...,praise ye lord heaven ; praise highest . prais...,[-0.07403488 -0.20329297 0.0287572 0.182462...,[ 0.06032175 -0.2944392 0.16987029 0.447312...,"[0.06032175, -0.2944392, 0.16987029, 0.4473129..."
299,299,Orthodox,Psalter,149,"Sing unto the Lord a new song, His praise is i...","sing unto lord new song , praise congregation ...",[-0.01585722 -0.07310608 -0.04004482 0.236639...,[ 0.0506989 -0.22018342 -0.01928143 0.459914...,"[0.0506989, -0.22018342, -0.01928143, 0.459914..."
300,300,Orthodox,Psalter,150,Praise God in His holy ones; praise Him in the...,praise god holy one ; praise firmament power ....,[ 3.44652246e-03 -2.73287113e-01 -2.01784975e-...,[ 0.06967841 -0.13542674 0.11822294 0.323153...,"[0.06967841, -0.13542674, 0.11822294, 0.323153..."

In [6]:
glove_vectors = {}
glove_vectors = {
    row["psalm_num"]: np.fromstring(
        str(row["glove_tfidf_vec"]).replace("[", "").replace("]", ""),
        sep=" "
    )
    for _, row in psalms.iterrows()
}

In [7]:
glove_vectors

{1: array([ 0.00603673, -0.15354042,  0.0516611 ,  0.08612016, -0.03848423,
         0.08526637,  0.03864759,  0.15004669,  0.07048849, -0.04124711,
        -0.00493622,  0.05137816,  0.10836737, -0.07812164,  0.04632644,
        -0.09993204,  0.21561742,  0.11942388, -0.10559052,  0.11505974,
        -0.32965721, -0.02357354, -0.05533156,  0.29347842, -0.07635234,
        -0.0988699 , -0.01237752,  0.01598731,  0.19744923, -0.0004418 ,
        -0.06811648, -0.20721046, -0.18295355,  0.0926963 , -0.05256963,
         0.175034  ,  0.3316947 ,  0.17777496, -0.11613299,  0.10753729,
         0.1374292 , -0.08315069,  0.04694427, -0.14707616, -0.020716  ,
        -0.32368071,  0.17493779, -0.18687928,  0.16806161, -0.20735587,
        -0.08087445, -0.03776397, -0.1090217 , -0.07498201, -0.00511915,
        -0.10591343, -0.00853767, -0.07302555,  0.02901452, -0.07338606,
         0.09482412,  0.15824688,  0.08555091,  0.19629198,  0.17955805,
        -0.2531808 ,  0.08668622,  0.11792758,  0.056465  , -0.06771738,
         0.11993277, -0.10506458,  0.02560613, -0.09098915,  0.05661698,
         0.03499203, -0.02446059, -0.01667472,  0.09424532,  0.1330259 ,
        -0.02519751, -0.02214835, -0.09644858,  0.07506838,  0.17858625,
         0.01385742, -0.19646012,  0.10207409,  0.09407979, -0.09795161,
         0.15655208, -0.11857495,  0.20799235,  0.11594345,  0.11400263,
        -0.05022742, -0.02132433,  0.03014845,  0.13997291,  0.21666624]),
 2: array([-0.03050032, -0.06582404,  0.10490528,  0.10727987,  0.10655961,
         0.00323488, -0.02118508,  0.06267149,  0.04747104,  0.03626106,
        -0.04221234,  0.02544569,  0.08255458, -0.06178011,  0.01325936,
        -0.15510706,  0.03149958,  0.00168399, -0.01298695,  0.1887923 ,
        -0.19949552,  0.05293485, -0.17052286,  0.13716246,  0.0171562 ,
         0.04802741, -0.02774619, -0.18097359,  0.17897957, -0.07263115,
        -0.03465036, -0.13885547, -0.13096037,  0.0928058 ,  0.10773341,
         0.16396638,  0.07030054,  0.05402663, -0.03870001,  0.15564684,
         0.06296284, -0.11018545, -0.0047655 , -0.00765994, -0.02451032,
        -0.19113837,  0.04377985, -0.1119698 , -0.04314767, -0.1422092 ,
        -0.14963721,  0.07310194, -0.11999657,  0.03624684,  0.1104619 ,
         0.04924781, -0.06947408, -0.14162754,  0.04156677, -0.08089549,
         0.11788056,  0.0211347 ,  0.06262422,  0.17502307,  0.12634307,
         0.06699021, -0.01110491, -0.0692522 ,  0.03183598,  0.02903426,
         0.07564939, -0.03435079,  0.09923006, -0.13481268,  0.01725176,
         0.04453201,  0.07540845, -0.21621689,  0.01004461,  0.02801795,
        -0.06028968, -0.00419259, -0.0886096 ,  0.07236014,  0.04291381,
        -0.0359378 , -0.11582102, -0.05258442,  0.17733744,  0.10204116,
         0.01420109, -0.15039051,  0.07046413,  0.06126844,  0.09839144,
        -0.06927984, -0.10546103,  0.04228056, -0.09199148,  0.1245294 ]),
 3: array([-0.04499422,  0.00200115,  0.06969146,  0.19099426,  0.20155604,
        -0.12433373,  0.06024399,  0.13916062,  0.05646278,  0.18689514,
        -0.02913416,  0.02357398,  0.23318598, -0.2094596 ,  0.28583201,
        -0.31936928,  0.13159603,  0.09886864, -0.02518887,  0.26560382,
        -0.38802843,  0.06225542, -0.29472265,  0.30352454, -0.0580303 ,
        -0.00317608, -0.05297122, -0.17711777,  0.20304742, -0.16322713,
        -0.11962816, -0.25221306, -0.21948629,  0.14657136,  0.0891238 ,
         0.23646578,  0.10105317,  0.12886287, -0.05621934,  0.42939365,
         0.23706559, -0.06404983, -0.15463636,  0.02900431, -0.12389946,
        -0.39753374,  0.131065  , -0.22270701,  0.1214245 , -0.17880307,
        -0.08813236,  0.11164204,  0.00111103,  0.01536913,  0.06654262,
         0.30352908, -0.14858617, -0.12107367,  0.10348885, -0.11520448,
         0.11684231,  0.10177   ,  0.18925624,  0.3171846 ,  0.15664531,
         0.03648236, -0.05057241,  0.04184613, -0.01590738, -0.03526888,
        -0.11948865, -0.30421184,  0.36516913, -0.07470281,  0.12677714,
         0.08088327,  0.23629553, -0.10126772,  0.02260808,  0.21084937,
        -0.17932776,  0.02288554, -0.07280326, -0.1257204 , -0.17578805,
         0.04167931, -0.34941223, -0.14665411,  0.33352088, -0.133203  ,
         0.08553018, -0.13681463, -0.01275155,  0.25196583,  0.2242822 ,
        -0.25002787, -0.06512725,  0.04263592, -0.18285817,  0.19138323]),
 4: array([-0.05744049,  0.02576862,  0.11662255,  0.1711126 ,  0.19366903,
        -0.01561026,  0.06472435,  0.12664607,  0.05808868,  0.2123452 ,
        -0.15760214,  0.0733706 ,  0.14940604, -0.09506715,  0.18089375,
        -0.16581313,  0.00611794, -0.05279772, -0.10485571,  0.32819937,
        -0.37399569,  0.15267882, -0.20259865,  0.20998214, -0.15116382,
         0.03038643, -0.14023902, -0.15229243,  0.13815935, -0.01493212,
        -0.06552509, -0.24761835, -0.1934855 ,  0.12689183,  0.1400019 ,
         0.30110204,  0.08160129,  0.14137268, -0.11259737,  0.3336525 ,
         0.13171634,  0.00304915, -0.16244109, -0.05060406, -0.17332839,
        -0.22221538,  0.07860153, -0.15158233,  0.06974876, -0.07074064,
        -0.1673473 , -0.0100938 , -0.06612348,  0.01193148, -0.05793822,
         0.02329207, -0.17117386, -0.18703565,  0.12945558, -0.23326094,
         0.10771411, -0.02951465,  0.19453558,  0.23365778,  0.20342211,
         0.12909359, -0.0201755 ,  0.01917791, -0.00123594, -0.0313652 ,
        -0.01357625, -0.10154896,  0.17461741, -0.07821118,  0.17819433,
         0.05065405,  0.08603025, -0.22455709,  0.07324788,  0.14295323,
        -0.0611953 , -0.04531938, -0.06552341,  0.03518793, -0.00917941,
         0.00669764, -0.32225963, -0.14542786,  0.25719355,  0.0144612 ,
        -0.04998317, -0.1529074 ,  0.1982221 ,  0.01349285,  0.20628139,
        -0.04588117, -0.10335851,  0.01067717, -0.15492282,  0.17716769]),
 5: array([ 1.42358885e-02, -3.05933038e-02,  7.69105068e-02,  2.32298296e-01,
         1.37836361e-01,  1.95083452e-02,  5.18722580e-02,  2.38982920e-01,
         3.66599891e-02,  2.30138987e-01, -1.19439111e-01, -8.82721760e-03,
         2.90923422e-02, -2.23375364e-01,  1.89354275e-01, -3.71993165e-01,
         7.94696969e-02, -9.75240349e-02, -3.32379675e-02,  2.57493936e-01,
        -4.18764910e-01,  1.74651368e-01, -3.21568526e-01,  2.14449539e-01,
        -1.15898776e-01, -5.80042976e-02, -5.56174002e-02, -2.05153318e-01,
         2.44443578e-01, -1.52418438e-01,  1.05352901e-02, -2.63743503e-01,
        -2.46596358e-01,  1.64955738e-01,  1.09495826e-01,  2.51597395e-01,
         1.31375192e-01,  3.01294460e-01, -1.60150517e-01,  2.28167985e-01,
         1.68614830e-01, -1.34919097e-02, -1.54712105e-01, -7.20319344e-03,
        -1.87384335e-01, -3.96056449e-01,  3.75911864e-02, -1.86823465e-01,
         1.29003031e-01, -1.43287173e-01, -1.66626319e-01, -3.48873601e-02,
        -2.33672709e-04,  1.08611919e-01,  8.40799160e-02,  2.10332154e-01,
        -9.59086173e-02, -3.17753555e-01,  1.52944795e-01, -1.59365629e-01,
         1.04421813e-01, -7.01700949e-02,  1.77957589e-01,  2.60545038e-01,
         1.63810998e-01,  8.86847403e-02,  3.57825065e-02,  1.32533814e-01,
         9.45959736e-02, -4.99552638e-02,  5.42800384e-02, -3.45692744e-01,
         2.23451066e-01, -3.08080567e-01,  2.74614842e-01,  1.33135549e-01,
         9.34397979e-02, -7.18629159e-02, -9.49551171e-04,  8.84571277e-02,
        -2.28194677e-01, -2.01974846e-02, -1.04220709e-01, -2.70754263e-02,
        -1.19709166e-02,  3.61187425e-02, -4.35041376e-01, -4.61345224e-02,
         2.81610040e-01,  3.01825208e-02,  1.46628218e-02, -2.78054052e-01,
         1.44573163e-01,  9.51372670e-02,  1.67379138e-01, -4.21243404e-02,
        -1.29822909e-01,  1.51689173e-01, -1.94355379e-01,  1.92344313e-01]),
 6: array([-0.04909382, -0.01447768,  0.01200207,  0.0162187 ,  0.27954267,
        -0.06313772, -0.01891216,  0.03332583,  0.03952032,  0.22740698,
        -0.16805615,  0.06274912,  0.12351942, -0.28856115,  0.1481497 ,
        -0.20754797,  0.07134381, -0.04199789, -0.05318308,  0.29633101,
        -0.22869055,  0.03075538, -0.31068661,  0.17859824, -0.01423582,
        -0.16425875, -0.03420221, -0.15835967,  0.05574922, -0.18231326,
        -0.12002752, -0.25646198, -0.06811478,  0.13359147,  0.08832506,
         0.18307839,  0.11063638,  0.1584797 , -0.01043068,  0.31440428,
         0.07706119, -0.05044152, -0.27548315, -0.0535638 , -0.07130218,
        -0.29625167, -0.05142666, -0.07649459,  0.09052019, -0.10988282,
        -0.05348345,  0.19871155, -0.02953372,  0.02131104, -0.04910564,
         0.30435106, -0.09446194, -0.26841027,  0.08362368, -0.06492492,
         0.06360555, -0.05316386,  0.13338402,  0.17045978, -0.01636972,
         0.08838839, -0.04393469,  0.03969904,  0.037452  , -0.01284821,
        -0.01031426, -0.24080974,  0.19999517, -0.15863804,  0.18369282,
         0.06559483,  0.03908395, -0.27290418,  0.14351828,  0.09065039,
        -0.05667768,  0.0016078 , -0.13062784, -0.0496168 ,  0.0224291 ,
        -0.16828351, -0.2099422 , -0.10523513,  0.20575673,  0.0274983 ,
         0.06741808, -0.18129717,  0.21156518,  0.13497262,  0.16488668,
        -0.08325337, -0.16751779,  0.13814932, -0.07073875,  0.09810115]),
 7: array([ 0.00990787,  0.00058483,  0.04921017,  0.17221373,  0.14770041,
        -0.0050101 ,  0.07993622,  0.06690732,  0.08475285,  0.08729396,
        -0.06081412,  0.05315371,  0.18484585, -0.11983469,  0.16604827,
        -0.22036455,  0.06051383, -0.0598727 , -0.00632166,  0.16006379,
        -0.28898314,  0.04919002, -0.26229915,  0.1647303 , -0.059105  ,
        -0.12564929, -0.11150931, -0.12039358,  0.15262105, -0.08672902,
        -0.12886224, -0.26561116, -0.20327986,  0.13676747,  0.0452346 ,
         0.20818142,  0.12339432,  0.02338245, -0.10149568,  0.19671923,
         0.14072591, -0.01714102, -0.1173032 , -0.01410374, -0.07557815,
        -0.30757766,  0.09810263, -0.11336299,  0.02120299, -0.15090027,
        -0.09741493,  0.03669982, -0.02070489,  0.0327787 , -0.0089013 ,
         0.15431078, -0.17371068, -0.17315168,  0.06634306, -0.07116622,
         0.08340419,  0.06411707,  0.11901821,  0.22129898,  0.14430055,
         0.04407468,  0.04613363,  0.02420309,  0.04128814,  0.03376582,
         0.03420502, -0.14401513,  0.21095663, -0.08739708,  0.13484118,
         0.07910542,  0.04249651, -0.12933703, -0.00846368,  0.15373436,
        -0.08036563, -0.0339874 , -0.13055133, -0.0874797 , -0.0324907 ,
        -0.05415779, -0.25586411, -0.16170622,  0.23215621,  0.05677927,
        -0.01397466, -0.21290419,  0.13073009,  0.0284668 ,  0.0639784 ,
        -0.18073598, -0.11483586,  0.01054182,  0.02679432,  0.183804  ]),
 8: array([ 0.10652784, -0.12947502,  0.1628642 , -0.03678845,  0.24593114,
         0.09976125,  0.04951902,  0.05834581,  0.1078882 ,  0.16327406,
        -0.08961074, -0.07206236,  0.20450903,  0.05758743,  0.34183592,
        -0.25970556,  0.02864521,  0.07671001, -0.20583553,  0.31036359,
        -0.2777394 ,  0.34681329, -0.1443896 ,  0.36354035,  0.01876654,
         0.11532924, -0.03562176, -0.13002217,  0.16611231, -0.23050847,
        -0.05823495, -0.06333969, -0.14228986,  0.0498042 ,  0.1444587 ,
         0.18223962,  0.06806167,  0.19274343, -0.11208419,  0.26790594,
         0.08561464, -0.10075263, -0.10688804,  0.05854029, -0.03406489,
        -0.23249608,  0.06081177, -0.23419259,  0.15589821, -0.03723317,
        -0.10959566,  0.06580306, -0.16592682,  0.05516794, -0.04425011,
         0.1191303 , -0.1228779 , -0.18246678,  0.02725754, -0.11996326,
         0.10568536, -0.03129991,  0.1642864 ,  0.28598141,  0.14688994,
         0.08497575, -0.09773097,  0.09017554,  0.02472261,  0.04113544,
        -0.01737489, -0.32054994,  0.07566981, -0.19687225,  0.07207665,
         0.11660009, -0.02805222, -0.12259825, -0.00731302,  0.09052673,
        -0.22517959, -0.05747386,  0.02089184, -0.1681226 , -0.01882881,
         0.08021582, -0.24151595, -0.20377759,  0.382832  ,  0.01210866,
         0.06814962, -0.23368171,  0.07886278,  0.02071637,  0.00994792,
        -0.04400047, -0.13068834,  0.05522219, -0.12556072,  0.15238996]),
 9: array([ 0.03817618, -0.02624198,  0.05404973,  0.10273113,  0.08889675,
         0.02992672,  0.11091819,  0.14774997,  0.08041897,  0.08659122,
        -0.05578552, -0.01200288,  0.09710824, -0.08071879,  0.14648361,
        -0.215518  ,  0.09714172, -0.05744959, -0.03663825,  0.13518163,
        -0.28006715,  0.06074234, -0.24141875,  0.28572607, -0.01876474,
        -0.00028733, -0.12099006, -0.10186911,  0.19791623, -0.04924341,
        -0.09336307, -0.2585983 , -0.17666287,  0.12774777,  0.1028556 ,
         0.16467338,  0.10974241,  0.10545254, -0.08481862,  0.26826724,
         0.11899569, -0.09143472, -0.1409078 ,  0.02092491, -0.05973806,
        -0.20393295,  0.10947365, -0.18439487,  0.05880964, -0.10728665,
        -0.13308589, -0.0509628 , -0.10359538,  0.01751362,  0.02650381,
         0.11998178, -0.08110287, -0.17774529,  0.09167553, -0.09434389,
         0.11235684,  0.03808437,  0.15681131,  0.19206103,  0.23692702,
        -0.00104553,  0.03963259,  0.07544141,  0.01882646, -0.02078705,
        -0.00233196, -0.13586315,  0.08342451, -0.17768654,  0.15174454,
         0.0069556 ,  0.03219707, -0.13423453,  0.02310305,  0.15122882,
        -0.02154867, -0.04886925, -0.07521065, -0.05127739,  0.02813805,
        -0.02271831, -0.23428317, -0.0517537 ,  0.16303058,  0.02825193,
         0.04560113, -0.22517489,  0.1545201 , -0.02341443,  0.07722067,
        -0.07586158, -0.13750632,  0.02992069, -0.07466887,  0.11719034]),
 10: array([-0.00082646, -0.05066767,  0.09539785,  0.03893643,  0.10758598,
         0.01791626,  0.10212927,  0.06036439,  0.15045547, -0.02696092,
        -0.05246491, -0.02858557,  0.12292661, -0.10207997,  0.06699578,
        -0.18776431,  0.06794197, -0.01010067,  0.05666207,  0.18901197,
        -0.32459937,  0.07827873, -0.15159659,  0.19269357, -0.10667527,
        -0.07923468, -0.15128213, -0.03356931,  0.19923877, -0.05129412,
        -0.12938823, -0.26025504, -0.18271198,  0.02782468,  0.06599995,
         0.18626882,  0.19618766,  0.05526474, -0.09138667,  0.24655197,
         0.17213856,  0.03301398, -0.03987377,  0.02546666, -0.08674918,
        -0.18165706,  0.09378825, -0.10882923,  0.05459887, -0.07947451,
        -0.11352045,  0.00872309, -0.12050105, -0.10946625,  0.03482964,
         0.03018501, -0.10778588, -0.09252635,  0.06145945, -0.05172604,
         0.0031185 ,  0.09456315,  0.08936038,  0.2314535 ,  0.17072944,
        -0.03623733,  0.0506227 ,  0.0461771 ,  0.08463184, -0.02432735,
         0.00815683, -0.01620674,  0.13790299, -0.03541473,  0.09360238,
         0.03083392, -0.00346212, -0.11453976,  0.06235623,  0.20246784,
         0.00539648,  0.02139914, -0.01937123,  0.0265268 ,  0.08975504,
         0.0070731 , -0.16544393, -0.09780484,  0.11774931,  0.02173634,
         0.04071895, -0.21453258,  0.13497343, -0.02877159,  0.10071306,
        -0.08042263, -0.13381847,  0.02800915,  0.09645518,  0.05591677]),
 11: array([ 0.0034344 , -0.03003008,  0.18790667,  0.02633313,  0.10055235,
         0.06743633,  0.08093432,  0.14032949,  0.03451347,  0.1509821 ,
         0.05530889,  0.04612187, -0.03728077, -0.02695553,  0.13923251,
        -0.11245402,  0.07180952, -0.1034924 , -0.05028414,  0.12402702,
        -0.30886284,  0.09139016, -0.10206471,  0.15919654, -0.12677383,
         0.00995439, -0.10168225, -0.08319729,  0.10630831, -0.0954211 ,
        -0.11294126, -0.1811583 , -0.2194626 ,  0.20195943,  0.08755292,
         0.18923895,  0.13515267,  0.06866382, -0.15866918,  0.10507422,
         0.20397657,  0.04379558, -0.02750126,  0.00577881, -0.07445882,
        -0.27604784,  0.06280874, -0.22437871,  0.13708531,  0.03756094,
        -0.0765119 ,  0.01468929, -0.10622769,  0.01284834, -0.05311891,
         0.02509404, -0.039676  , -0.22340821,  0.08533252, -0.05811196,
         0.04598342, -0.12830836,  0.02638933,  0.16195534,  0.14997359,
        -0.02211207, -0.03431465,  0.04926166,  0.09364831,  0.00133498,
         0.02589741, -0.13319612,  0.11810012, -0.18105191,  0.19363813,
         0.10108558,  0.10134289, -0.14612326,  0.03578624,  0.06803815,
        -0.09314042, -0.03565761, -0.03204143,  0.05175358,  0.13798011,
        -0.00791895, -0.12349653,  0.0450322 ,  0.10745202, -0.02610691,
        -0.02917829, -0.14922461,  0.0913916 ,  0.08007087,  0.04031983,
         0.00506677, -0.05381699, -0.05138946, -0.00866068,  0.21253911]),
 12: array([ 0.05116587,  0.01326856, -0.01037118,  0.2528128 ,  0.29801217,
        -0.07604195,  0.13313236,  0.17576712,  0.02218013,  0.2513838 ,
        -0.13850734,  0.14284752,  0.20052183, -0.08782657,  0.45168451,
        -0.3165989 ,  0.10741028, -0.15828839, -0.15734639,  0.26171636,
        -0.50046416,  0.08901751, -0.40510161,  0.38127732, -0.13434702,
         0.0185715 , -0.20458776, -0.24846117,  0.13628957, -0.02247483,
        -0.18502056, -0.29627335, -0.31237763,  0.20222262,  0.04748826,
         0.23198701,  0.1033104 ,  0.16034927, -0.16076086,  0.36434587,
         0.17441201, -0.07099468, -0.16134037,  0.04219784, -0.28242298,
        -0.46064407,  0.11371294, -0.08397394, -0.00382401, -0.21595925,
        -0.24057236,  0.15638252,  0.10318476, -0.01710601,  0.10344355,
         0.25509831, -0.04852428, -0.18781811,  0.14713586, -0.05338497,
         0.04637434, -0.0238581 ,  0.37033639,  0.2235198 ,  0.21184999,
        -0.00695663,  0.01399177,  0.06574593,  0.14295526, -0.0150928 ,
         0.10551138, -0.3014345 ,  0.34486863, -0.14267514,  0.23652952,
         0.10720758,  0.17273447, -0.18893843, -0.02093714,  0.12578701,
        -0.08155409, -0.1018396 , -0.11771439, -0.14621524, -0.12961634,
        -0.05496   , -0.47324707, -0.26842195,  0.3393786 ,  0.14020599,
         0.0435224 , -0.33570288,  0.2990444 ,  0.10118523,  0.28768234,
        -0.21270497, -0.10763684, -0.08174784, -0.11180263,  0.26439423]),
 13: array([-0.13540851,  0.07795917, -0.01807517,  0.2532023 ,  0.20702233,
        -0.0008482 ,  0.01802757,  0.11348132, -0.13057271,  0.16081179,
        -0.16194456,  0.02198905,  0.1563258 , -0.30117866,  0.02132103,
        -0.16903405,  0.15683628, -0.12047422,  0.13383897,  0.18024311,
        -0.2782348 , -0.06844938, -0.04732311,  0.28224118, -0.09665352,
        -0.12087687, -0.14791266, -0.09722284,  0.13526392, -0.01315872,
        -0.10156493, -0.3289952 , -0.30418906,  0.25818185, -0.02785024,
         0.2552847 ,  0.15820597,  0.16031718, -0.02503558,  0.35568745,
         0.29843213, -0.0186897 ,  0.05943058,  0.06380222, -0.13491338,
        -0.29543005,  0.2199044 , -0.1967095 , -0.07197946, -0.14328565,
        -0.22035784,  0.09673601, -0.13115306, -0.05866407,  0.00160948,
        -0.01054092, -0.05426019, -0.30607883,  0.04200779, -0.21512468,
        -0.03354787,  0.00609596,  0.14328464,  0.25279142,  0.21885744,
         0.03925616, -0.09162954,  0.01731074, -0.00773059, -0.08596269,
         0.07824028, -0.02634591,  0.09780449, -0.11425735,  0.12554005,
        -0.01244308,  0.05230328, -0.14650819,  0.03687198,  0.29994703,
        -0.05048278, -0.13780299, -0.16577631,  0.14806998,  0.0200912 ,
        -0.02370979, -0.2326646 , -0.1488646 ,  0.02182142,  0.09261685,
         0.08762987, -0.13507435,  0.0119959 , -0.0059019 ,  0.05574974,
        -0.14369838, -0.12743985, -0.00604079, -0.03021045,  0.17400472]),
 14: array([-0.04213398,  0.05922197,  0.11277731,  0.09655503,  0.1374211 ,
        -0.00234359, -0.02729219,  0.04513874,  0.12960591,  0.00533225,
        -0.00574646, -0.04623093, -0.06384596, -0.01397026,  0.12226671,
        -0.14034971,  0.11191297, -0.06117243, -0.04011763,  0.032928  ,
        -0.2296041 ,  0.06913275, -0.12625363,  0.1543577 , -0.13110394,
        -0.05348111, -0.0841698 , -0.05260974,  0.12399404, -0.01693482,

In [8]:
 # get embedding dimension
embedding_dim = len(next(iter(glove_vectors.values())))
print(embedding_dim)

100

In [9]:
import pickle 
import os
print(os.getcwd())

# getting the pickle file ready to be used
with open("../data/psalms_tfidf_matrix.pickle", "rb") as file:
    tfidf_matrix = pickle.load(file)

/opt/notebooks/psalms_nlp_sp26/query_compare

In [10]:
# Number of documents
N = tfidf_matrix.shape[0]

# Count how many docs contain each word
df = np.sum(tfidf_matrix > 0, axis=0)  # document frequency

# Compute IDF
idf_weights = np.log((N + 1) / (df + 1)) + 1  # standard smoothed IDF

# Map to dict
idf_weights = dict(zip(tfidf_matrix.columns, idf_weights))

In [11]:
idf_weights

{'aaron': 3.8772136733186535,
 'abandon': 5.100989104940769,
 'abasement': 6.017279836814924,
 'abated': 6.017279836814924,
 'abhor': 5.324132656254979,
 'abhorred': 4.407841924380824,
 'abhors': 6.017279836814924,
 'abide': 5.100989104940769,
 'abides': 5.324132656254979,
 'abideth': 5.61181472870676,
 'abimelech': 5.61181472870676,
 'abiram': 5.61181472870676,
 'able': 5.100989104940769,
 'abolish': 5.61181472870676,
 'abominable': 5.100989104940769,
 'abomination': 5.61181472870676,
 'abound': 5.61181472870676,
 'abounding': 5.100989104940769,
 'about': 4.225520367586869,
 'above': 5.324132656254979,
 'abraham': 5.100989104940769,
 'abroad': 4.764516868319556,
 'absalom': 6.017279836814924,
 'abundance': 3.820055259478705,
 'abundant': 5.100989104940769,
 'abundantly': 5.100989104940769,
 'abyss': 6.017279836814924,
 'accept': 5.61181472870676,
 'accomplished': 6.017279836814924,
 'accomplishment': 6.017279836814924,
 'according': 2.9492269016813073,
 'accordingly': 6.017279836814924,
 'account': 4.918667548146814,
 'accounted': 6.017279836814924,
 'accursed': 6.017279836814924,
 'accusation': 5.61181472870676,
 'accuse': 4.918667548146814,
 'accused': 5.61181472870676,
 'accuser': 5.61181472870676,
 'acknowledge': 5.324132656254979,
 'acknowledged': 6.017279836814924,
 'acquaintance': 5.100989104940769,
 'acquainted': 6.017279836814924,
 'acquired': 5.61181472870676,
 'acquitted': 6.017279836814924,
 'act': 3.7659880382084294,
 'acted': 6.017279836814924,
 'acting': 5.61181472870676,
 'add': 4.764516868319556,
 'added': 5.100989104940769,
 'adopt': 6.017279836814924,
 'adorned': 5.100989104940769,
 'adulterer': 5.61181472870676,
 'advantage': 5.61181472870676,
 'adversary': 5.61181472870676,
 'adversity': 5.61181472870676,
 'aermon': 6.017279836814924,
 'afar': 4.312531744576499,
 'afflict': 3.820055259478705,
 'afflicted': 4.513202440038651,
 'afflicting': 6.017279836814924,
 'affliction': 3.0215475632609334,
 'afflicts': 5.61181472870676,
 'afire': 6.017279836814924,
 'aflame': 6.017279836814924,
 'afore': 6.017279836814924,
 'afraid': 3.532373187026924,
 'after': 6.017279836814924,
 'afterwards': 5.324132656254979,
 'again': 4.764516868319556,
 'age': 2.926237383456608,
 'aggeus': 5.100989104940769,
 'aha': 5.324132656254979,
 'aid': 5.61181472870676,
 'ailed': 6.017279836814924,
 'air': 4.918667548146814,
 'alarm': 6.017279836814924,
 'alien': 4.764516868319556,
 'alienated': 6.017279836814924,
 'alive': 4.764516868319556,
 'all': 5.100989104940769,
 'alleluia': 3.7659880382084294,
 'allow': 5.61181472870676,
 'allowed': 6.017279836814924,
 'ally': 6.017279836814924,
 'almost': 4.764516868319556,
 'aloe': 6.017279836814924,
 'alone': 3.7659880382084294,
 'along': 5.324132656254979,
 'aloof': 6.017279836814924,
 'aloud': 5.100989104940769,
 'also': 2.7030938321423985,
 'alsothe': 6.017279836814924,
 'alsounable': 6.017279836814924,
 'altar': 4.312531744576499,
 'although': 5.61181472870676,
 'altogether': 4.513202440038651,
 'alway': 5.61181472870676,
 'always': 4.071369687759612,
 'amalek': 5.61181472870676,
 'ambassador': 5.61181472870676,
 'ambush': 5.61181472870676,
 'amen': 4.6309854756950335,
 'ammon': 5.61181472870676,
 'among': 2.315977862702431,
 'amorites': 5.100989104940769,
 'ancient': 6.017279836814924,
 'and': 6.017279836814924,
 'anew': 5.61181472870676,
 'angel': 3.6193845640165536,
 'anger': 3.244691114575143,
 'angered': 6.017279836814924,
 'angry': 3.57493280144572,
 'anguish': 5.100989104940769,
 'animal': 4.918667548146814,
 'annul': 6.017279836814924,
 'anoint': 5.324132656254979,
 'anointed': 3.6193845640165536,
 'anointing': 6.017279836814924,
 'another': 4.6309854756950335,
 'answer': 5.100989104940769,
 'answered': 6.017279836814924,
 'anticipated': 6.017279836814924,
 'anxious': 6.017279836814924,
 'anyone': 5.61181472870676,
 'apart': 5.61181472870676,
 'apparel': 6.017279836814924,
 'appear': 4.918667548146814,
 'appeared': 5.61181472870676,
 'appeareth': 6.017279836814924,
 'appeased': 6.017279836814924,
 'apple': 5.61181472870676,
 'appoint': 5.61181472870676,
 'appointed': 4.407841924380824,
 'appointedst': 6.017279836814924,
 'appointeth': 5.61181472870676,
 'appoints': 6.017279836814924,
 'approach': 6.017279836814924,
 'arabia': 5.61181472870676,
 'arabian': 6.017279836814924,
 'aright': 5.100989104940769,
 'arise': 3.3431311873883955,
 'arisen': 6.017279836814924,
 'arises': 6.017279836814924,
 'ariseth': 6.017279836814924,
 'ark': 5.61181472870676,
 'arm': 3.6659045796514467,
 'armed': 6.017279836814924,
 'army': 4.6309854756950335,
 'arose': 4.407841924380824,
 'around': 4.1454776599133325,
 'aroused': 6.017279836814924,
 'arrangement': 6.017279836814924,
 'array': 5.61181472870676,
 'arrayed': 5.61181472870676,
 'arrogance': 4.918667548146814,
 'arrogant': 4.513202440038651,
 'arrogantly': 5.324132656254979,
 'arrow': 3.4915511925066687,
 'art': 2.926237383456608,
 'asaph': 4.1454776599133325,
 'ascend': 4.918667548146814,
 'ascended': 4.918667548146814,
 'ascendeth': 6.017279836814924,
 'ascent': 3.820055259478705,
 'ascribe': 5.61181472870676,
 'ash': 5.100989104940769,
 'ashamed': 3.4145901513705406,
 'aside': 4.071369687759612,
 'ask': 4.918667548146814,
 'asked': 4.764516868319556,
 'asking': 5.324132656254979,
 'asleep': 5.100989104940769,
 'asp': 4.764516868319556,
 'ass': 5.61181472870676,
 'assail': 6.017279836814924,
 'assemble': 6.017279836814924,
 'assembled': 5.324132656254979,
 'assembly': 4.071369687759612,
 'associate': 6.017279836814924,
 'assur': 6.017279836814924,
 'assyria': 6.017279836814924,
 'assyrian': 5.324132656254979,
 'astray': 4.513202440038651,
 'asunder': 5.100989104940769,
 'ate': 4.513202440038651,
 'atone': 6.017279836814924,
 'atonement': 6.017279836814924,
 'attack': 6.017279836814924,
 'attain': 6.017279836814924,
 'attend': 4.00237681627266,
 'attended': 6.017279836814924,
 'attention': 6.017279836814924,
 'attentive': 5.324132656254979,
 'attentively': 6.017279836814924,
 'authority': 5.61181472870676,
 'avenger': 5.61181472870676,
 'avenges': 6.017279836814924,
 'avengeth': 6.017279836814924,
 'avenging': 6.017279836814924,
 'await': 6.017279836814924,
 'awaited': 6.017279836814924,
 'awake': 4.407841924380824,
 'awaked': 6.017279836814924,
 'awaken': 5.324132656254979,
 'awakened': 5.61181472870676,
 'awaketh': 6.017279836814924,
 'aware': 6.017279836814924,
 'away': 2.256079721121362,
 'awe': 6.017279836814924,
 'awesome': 6.017279836814924,
 'awoke': 5.324132656254979,
 'ax': 5.61181472870676,
 'axe': 6.017279836814924,
 'baalpeor': 5.61181472870676,
 'babbling': 6.017279836814924,
 'babe': 5.324132656254979,
 'baby': 6.017279836814924,
 'babylon': 5.100989104940769,
 'back': 3.0215475632609334,
 'backward': 5.324132656254979,
 'bag': 6.017279836814924,
 'balance': 6.017279836814924,
 'band': 5.61181472870676,
 'banished': 5.61181472870676,
 'bar': 5.100989104940769,
 'barb': 6.017279836814924,
 'barbarous': 6.017279836814924,
 'barren': 5.324132656254979,
 'barrenness': 6.017279836814924,
 'bashan': 4.764516868319556,
 'basilisk': 5.61181472870676,
 'basket': 5.61181472870676,
 'bathsheba': 5.61181472870676,
 'battle': 4.225520367586869,
 'be': 5.61181472870676,
 'bear': 5.324132656254979,
 'beard': 5.61181472870676,
 'bearest': 6.017279836814924,
 'bearing': 6.017279836814924,
 'beast': 3.8772136733186535,
 'beat': 6.017279836814924,
 'beaten': 6.017279836814924,
 'beautified': 6.017279836814924,
 'beautiful': 6.017279836814924,
 'beautifully': 6.017279836814924,
 'beauty': 3.8772136733186535,
 'became': 3.378222507199666,
 'become': 2.9968549506705617,
 'becomes': 6.017279836814924,
 'becometh': 5.61181472870676,
 'bed': 3.9378382951350885,
 'bee': 5.61181472870676,
 'befall': 5.61181472870676,
 'before': 6.017279836814924,
 'beg': 6.017279836814924,
 'beggar': 5.61181472870676,
 'begging': 5.61181472870676,
 'begin': 5.61181472870676,
 'beginning': 4.1454776599133325,
 'begotten': 4.918667548146814,
 'begun': 6.017279836814924,
 'behalf': 5.61181472870676,
 'behaves': 6.017279836814924,
 'beheaded': 6.017279836814924,
 'beheld': 4.513202440038651,
 'behind': 4.764516868319556,
 'behold': 2.5995531532015583,
 'beholdest': 6.017279836814924,
 'beholdeth': 6.017279836814924,
 'beholds': 6.017279836814924,
 'being': 5.61181472870676,
 'believe': 4.918667548146814,
 'believed': 4.764516868319556,
 'belly': 4.513202440038651,
 'belong': 5.61181472870676,
 'belongeth': 5.324132656254979,
 'belongs': 6.017279836814924,
 'beloved': 4.071369687759612,
 'belt': 6.017279836814924,
 'bend': 4.6309854756950335,
 'bending': 6.017279836814924,
 'benefactor': 5.61181472870676,
 'benefit': 5.61181472870676,
 'benjamin': 4.918667548146814,
 'bent': 4.918667548146814,
 'bereavement': 6.017279836814924,
 'beset': 6.017279836814924,
 'beside': 4.764516868319556,
 'besides': 5.324132656254979,
 'best': 5.324132656254979,
 'betrayed': 6.017279836814924,
 'better': 4.407841924380824,
 'bewilderment': 6.017279836814924,
 'beyond': 5.324132656254979,
 'billow': 5.100989104940769,
 'bind': 5.61181472870676,
 'bindeth': 6.017279836814924,
 'bird': 4.764516868319556,
 'birth': 4.918667548146814,
 'bit': 5.61181472870676,
 'bitter': 5.61181472870676,
 'bitterness': 5.324132656254979,
 'blame': 5.61181472870676,
 'blameless': 4.071369687759612,
 'blamelessly': 6.017279836814924,
 'bless': 2.778601384650544,
 'blessed': 2.4337608983588144,
 'blesses': 5.61181472870676,
 'blesseth': 6.017279836814924,
 'blessing': 3.8772136733186535,
 'blind': 5.61181472870676,
 'block': 4.407841924380824,
 'blood': 3.3092296357127142,
 'bloodguiltiness': 5.61181472870676,
 'bloody': 5.324132656254979,
 'blossom': 5.61181472870676,
 'blot': 5.61181472870676,
 'blotted': 4.918667548146814,
 'blow': 4.918667548146814,
 'boar': 6.017279836814924,
 'boast': 3.9378382951350885,
 'boasted': 5.324132656254979,
 'boastest': 6.017279836814924,
 'boastful': 6.017279836814924,
 'boasting': 6.017279836814924,
 'body': 4.513202440038651,
 'boldly': 5.61181472870676,
 'bond': 5.324132656254979,
 'bondage': 6.017279836814924,
 'bone': 3.3431311873883955,
 'book': 4.764516868319556,
 'booty': 5.61181472870676,
 'border': 4.764516868319556,
 'bore': 5.61181472870676,
 'born': 4.407841924380824,
 'borne': 5.61181472870676,
 'borroweth': 6.017279836814924,
 'borrows': 6.017279836814924,
 'bosom': 4.407841924380824,
 'bough': 5.61181472870676,
 'bound': 4.513202440038651,
 'boundary': 5.324132656254979,
 'bountifully': 5.61181472870676,
 'bow': 3.2139194559083895,
 'bowed': 4.6309854756950335,
 'bowel': 5.324132656254979,
 'bowing': 6.017279836814924,
 'brake': 5.100989104940769,
 'brakest': 6.017279836814924,
 'branch': 5.324132656254979,
 'brass': 5.61181472870676,
 'breach': 5.324132656254979,
 'bread': 3.4915511925066687,
 'break': 4.407841924380824,
 'breaketh': 6.017279836814924,
 'breaking': 6.017279836814924,
 'breast': 5.324132656254979,
 'breath': 4.00237681627266,
 'breathes': 6.017279836814924,
 'breathing': 6.017279836814924,
 'breeze': 5.61181472870676,
 'briar': 6.017279836814924,
 'bribe': 5.100989104940769,
 'bridal': 6.017279836814924,
 'bridegroom': 5.61181472870676,
 'bridle': 5.61181472870676,
 'bright': 5.100989104940769,
 'brighten': 6.017279836814924,
 'brightness': 4.918667548146814,
 'brimming': 6.017279836814924,
 'brimstone': 5.61181472870676,
 'bring': 2.926237383456608,
 'bringeth': 5.61181472870676,
 'bringing': 5.324132656254979,
 'brings': 5.61181472870676,
 'broad': 5.324132656254979,
 'broke': 4.312531744576499,
 'broken': 3.532373187026924,
 'brokenhearted': 5.61181472870676,
 'bronze': 5.61181472870676,
 'brook': 4.918667548146814,
 'brother': 3.9378382951350885,
 'brought': 3.0468653712452234,
 'broughtest': 6.017279836814924,
 'buckler': 6.017279836814924,
 'build': 4.513202440038651,
 'builded': 5.61181472870676,
 'builder': 5.61181472870676,
 'building': 6.017279836814924,
 'built': 4.312531744576499,
 'bull': 4.407841924380824,
 'bullock': 5.61181472870676,
 'bulwark': 6.017279836814924,
 'burden': 5.324132656254979,
 'buried': 6.017279836814924,
 'burn': 4.071369687759612,
 'burned': 4.513202440038651,
 'burneth': 6.017279836814924,
 'burning': 6.017279836814924,
 'burnt': 4.513202440038651,
 'burntoffering': 6.017279836814924,
 'burntofferings': 6.017279836814924,
 'burst': 6.017279836814924,
 'bursting': 6.017279836814924,
 'bury': 5.61181472870676,
 'bush': 6.017279836814924,
 'business': 5.61181472870676,
 'but': 6.017279836814924,
 'by': 6.017279836814924,
 'byword': 5.100989104940769,
 'calamity': 6.017279836814924,
 'caldron': 6.017279836814924,
 'calf': 4.918667548146814,
 'call': 2.9968549506705617,
 'called': 3.532373187026924,
 'calledst': 6.017279836814924,
 'calleth': 5.61181472870676,
 'calm': 6.017279836814924,
 'calmed': 6.017279836814924,
 'calve': 6.017279836814924,
 'came': 3.57493280144572,
 'camp': 4.918667548146814,
 'can': 5.324132656254979,
 'canaan': 4.764516868319556,
 'cankerworm': 6.017279836814924,
 'captive': 4.513202440038651,
 'captivity': 4.071369687759612,
 'captor': 6.017279836814924,
 'care': 4.918667548146814,
 'cared': 6.017279836814924,
 'carried': 5.324132656254979,
 'carry': 5.324132656254979,
 'carrying': 6.017279836814924,
 'carved': 5.61181472870676,
 'cassia': 5.61181472870676,
 'cast': 2.839226006466979,
 'castedst': 6.017279836814924,
 'castest': 6.017279836814924,
 'casteth': 5.61181472870676,
 'casting': 5.61181472870676,
 'cataract': 6.017279836814924,
 'catch': 5.61181472870676,
 'caterpillar': 6.017279836814924,
 'caterpiller': 6.017279836814924,
 'cattle': 3.9378382951350885,
 'caught': 5.61181472870676,
 'cauldron': 5.324132656254979,
 'cause': 3.244691114575143,
 'caused': 4.513202440038651,
 'causeth': 6.017279836814924,
 'cave': 5.61181472870676,
 'cease': 4.764516868319556,
 'ceased': 4.918667548146814,
 'cedar': 4.1454776599133325,
 'celebrate': 5.61181472870676,
 'chaff': 5.61181472870676,
 'chain': 5.324132656254979,
 'chamber': 4.764516868319556,
 'champion': 5.61181472870676,
 'change': 4.764516868319556,
 'changed': 3.9378382951350885,
 'charge': 6.017279836814924,
 'charged': 6.017279836814924,
 'chariot': 5.100989104940769,
 'charm': 5.61181472870676,
 'charmer': 5.61181472870676,
 'chased': 6.017279836814924,
 'chasten': 4.764516868319556,
 'chastened': 4.918667548146814,
 'chastening': 6.017279836814924,
 'chastises': 6.017279836814924,
 'chastiseth': 6.017279836814924,
 'chatter': 6.017279836814924,
 'cheerful': 6.017279836814924,
 'cherub': 4.764516868319556,
 'chief': 5.61181472870676,
 'child': 3.099509104730645,
 'childbirth': 6.017279836814924,
 'childish': 6.017279836814924,
 'childrens': 5.61181472870676,
 'choice': 6.017279836814924,
 'choose': 5.61181472870676,
 'chooses': 6.017279836814924,
 'chose': 4.407841924380824,
 'chosen': 3.7659880382084294,
 'christ': 6.017279836814924,
 'church': 4.6309854756950335,
 'circle': 6.017279836814924,
 'circled': 6.017279836814924,
 'circuit': 5.324132656254979,
 'citadel': 6.017279836814924,
 'city': 3.1550789558854557,
 'clap': 4.918667548146814,
 'clave': 5.61181472870676,
 'clay': 5.61181472870676,
 'clean': 5.61181472870676,
 'cleanness': 6.017279836814924,
 'cleanse': 5.100989104940769,
 'cleansed': 5.100989104940769,
 'cleave': 4.764516868319556,
 'cleaved': 4.513202440038651,
 'cleaves': 5.61181472870676,
 'cliff': 6.017279836814924,
 'cling': 6.017279836814924,
 'cloak': 5.61181472870676,
 'clod': 5.61181472870676,
 'close': 5.324132656254979,
 'closely': 5.61181472870676,
 'clothe': 5.100989104940769,
 'clothed': 4.225520367586869,
 'clothes': 6.017279836814924,
 'clothing': 6.017279836814924,
 'cloud': 3.3431311873883955,
 'coal': 4.764516868319556,
 'coast': 6.017279836814924,
 'cold': 6.017279836814924,
 'color': 6.017279836814924,
 'colour': 6.017279836814924,
 'combat': 6.017279836814924,
 'come': 2.353718190685278,
 'comeliness': 5.61181472870676,
 'cometh': 4.407841924380824,
 'comfort': 4.764516868319556,
 'comforted': 4.225520367586869,
 'comforter': 6.017279836814924,
 'coming': 4.513202440038651,
 'command': 4.764516868319556,
 'commanded': 3.714694743820879,
 'commandest': 6.017279836814924,
 'commandment': 3.9378382951350885,
 'commanments': 6.017279836814924,
 'commit': 5.61181472870676,
 'committed': 5.61181472870676,
 'communed': 5.61181472870676,
 'compact': 6.017279836814924,
 'compactness': 6.017279836814924,
 'companion': 5.100989104940769,
 'company': 5.324132656254979,
 'compared': 5.100989104940769,
 'compass': 4.764516868319556,
 'compassed': 4.225520367586869,
 'compassion': 3.9378382951350885,
 'compassionate': 4.6309854756950335,
 'complained': 6.017279836814924,
 'complete': 6.017279836814924,
 'completely': 5.100989104940769,
 'compunction': 6.017279836814924,
 'concealed': 6.017279836814924,
 'conceived': 5.100989104940769,
 'concerning': 3.2139194559083895,
 'condemn': 5.100989104940769,
 'condemned': 5.61181472870676,
 'confess': 5.100989104940769,
 'confesseth': 6.017279836814924,
 'confine': 6.017279836814924,
 'confirmed': 5.61181472870676,
 'confounded': 4.6309854756950335,
 'confusion': 4.918667548146814,
 'congregation': 3.7659880382084294,
 'conquered': 6.017279836814924,
 'consecrated': 6.017279836814924,
 'consecration': 6.017279836814924,
 'consent': 6.017279836814924,
 'consented': 6.017279836814924,
 'consider': 4.407841924380824,
 'considered': 5.324132656254979,
 'considereth': 5.61181472870676,
 'consoled': 6.017279836814924,
 'conspiracy': 6.017279836814924,
 'consulted': 5.324132656254979,
 'consume': 5.61181472870676,
 'consumed': 4.407841924380824,
 'contemned': 6.017279836814924,
 'contempt': 4.407841924380824,
 'contemptuously': 6.017279836814924,
 'continually': 3.4523304793533875,
 'continue': 4.918667548146814,
 'continued': 5.61181472870676,
 'continues': 5.324132656254979,
 'continueth': 5.61181472870676,
 'contradict': 6.017279836814924,
 'contradiction': 5.61181472870676,
 'contrite': 5.61181472870676,
 'convert': 6.017279836814924,
 'converted': 6.017279836814924,
 'converting': 5.61181472870676,
 'cord': 5.61181472870676,
 'corn': 6.017279836814924,
 'corner': 5.61181472870676,
 'corpse': 6.017279836814924,
 'correct': 5.61181472870676,
 'corrected': 5.324132656254979,
 'corrupt': 4.407841924380824,
 'corrupted': 6.017279836814924,
 'corruption': 4.513202440038651,
 'couch': 5.324132656254979,
 'could': 4.764516868319556,
 'council': 5.324132656254979,
 'counsel': 3.378222507199666,
 'count': 6.017279836814924,
 'counted': 4.6309854756950335,
 'countenance': 3.57493280144572,
 'country': 5.61181472870676,
 'courage': 5.324132656254979,
 'courageous': 5.61181472870676,
 'course': 6.017279836814924,
 'court': 3.6659045796514467,
 'covenant': 3.378222507199666,
 'cover': 4.407841924380824,
 'covered': 3.4523304793533875,
 'coverest': 6.017279836814924,
 'covereth': 6.017279836814924,
 'covering': 5.61181472870676,
 'covert': 5.61181472870676,
 'covet': 6.017279836814924,
 'covetousness': 6.017279836814924,
 'cowardice': 6.017279836814924,
 'craftily': 6.017279836814924,
 'crafty': 6.017279836814924,
 'create': 5.324132656254979,
 'created': 4.1454776599133325,
 'creation': 5.100989104940769,
 'creature': 5.324132656254979,
 'creditor': 5.61181472870676,
 'creepeth': 6.017279836814924,
 'creeping': 5.100989104940769,
 'cried': 3.072840857648484,
 'crooked': 4.764516868319556,
 'cross': 6.017279836814924,
 'crouch': 6.017279836814924,
 'crown': 4.6309854756950335,
 'crowned': 5.100989104940769,
 'crowneth': 6.017279836814924,
 'crush': 4.6309854756950335,
 'crushed': 5.100989104940769,
 'cry': 3.244691114575143,
 'cup': 4.312531744576499,
 'curdled': 5.100989104940769,
 'curse': 4.764516868319556,
 'cursed': 5.324132656254979,
 'cursing': 4.918667548146814,
 'curtain': 5.61181472870676,
 'cush': 6.017279836814924,
 'cut': 3.820055259478705,
 'cymbal': 5.61181472870676,
 'dagger': 6.017279836814924,
 'daily': 5.100989104940769,
 'dam': 6.017279836814924,
 'dampen': 6.017279836814924,
 'damsel': 6.017279836814924,
 'dance': 5.100989104940769,

In [12]:
idf_weights.get('aaron', 1.0)

3.8772136733186535

In [13]:
import numpy as np
import re

def compute_query_embedding(query):
    # Better tokenization: removes punctuation properly
    tokens = re.findall(r"\b\w+\b", query.lower())

    numerator = np.zeros(embedding_dim, dtype=np.float32)
    denominator = 0.0

    valid_tokens = 0
    
    '''
    print("Tokens:", tokens)
    print("Sample keys:", list(glove_vectors.keys())[:10])

    for word in tokens:
        print(f"{word}: {word in idf_weights}")
    '''

    for word in tokens:
        if word in idf_weights:
            weight = idf_weights.get(word, 1.0)
            # print(weight)
            numerator += idf_weights[word] * weight
            denominator += weight
            valid_tokens += 1

    # If nothing matched GloVe vocabulary
    if valid_tokens == 0:
        # return zero vector instead of None (more stable for pipelines)
        return np.zeros(embedding_dim)

    return numerator / denominator

print(compute_query_embedding('query aaron for ever after'))

[4.6420608 4.6420608 4.6420608 4.6420608 4.6420608 4.6420608 4.6420608
 4.6420608 4.6420608 4.6420608 4.6420608 4.6420608 4.6420608 4.6420608
 4.6420608 4.6420608 4.6420608 4.6420608 4.6420608 4.6420608 4.6420608
 4.6420608 4.6420608 4.6420608 4.6420608 4.6420608 4.6420608 4.6420608
 4.6420608 4.6420608 4.6420608 4.6420608 4.6420608 4.6420608 4.6420608
 4.6420608 4.6420608 4.6420608 4.6420608 4.6420608 4.6420608 4.6420608
 4.6420608 4.6420608 4.6420608 4.6420608 4.6420608 4.6420608 4.6420608
 4.6420608 4.6420608 4.6420608 4.6420608 4.6420608 4.6420608 4.6420608
 4.6420608 4.6420608 4.6420608 4.6420608 4.6420608 4.6420608 4.6420608
 4.6420608 4.6420608 4.6420608 4.6420608 4.6420608 4.6420608 4.6420608
 4.6420608 4.6420608 4.6420608 4.6420608 4.6420608 4.6420608 4.6420608
 4.6420608 4.6420608 4.6420608 4.6420608 4.6420608 4.6420608 4.6420608
 4.6420608 4.6420608 4.6420608 4.6420608 4.6420608 4.6420608 4.6420608
 4.6420608 4.6420608 4.6420608 4.6420608 4.6420608 4.6420608 4.6420608
 4.6420608 4.6420608]

In [14]:
import numpy as np

def ensure_array(x):
    if isinstance(x, str):
        # string like "[0.04116335 -0.16281123 ...]"
        x = x.strip("[]")  # remove brackets
        numbers = [float(n) for n in x.split()]
        return np.array(numbers, dtype=float)
    elif isinstance(x, list):
        # list -> array
        return np.array(x, dtype=float)
    elif isinstance(x, np.ndarray):
        # already array, do nothing
        return x
    else:
        # fallback to zero vector if something else
        return np.zeros(300)  # replace 300 with your embedding_dim

psalms["glove_tfidf_vec"] = psalms["glove_tfidf_vec"].apply(ensure_array)

# Check
print(type(psalms["glove_tfidf_vec"].iloc[0]))  # <class 'numpy.ndarray'>
print(psalms["glove_tfidf_vec"].iloc[0].shape)

<class 'numpy.ndarray'>
(100,)

In [15]:

# Check
print(type(psalms["glove_tfidf_vec"].iloc[0]))  # should be <class 'numpy.ndarray'>
print(psalms["glove_tfidf_vec"].iloc[0].shape)  # should show (embedding_dim,)

<class 'numpy.ndarray'>
(100,)

In [16]:
print(type(psalms["glove_tfidf_vec"].iloc[0]))  # <class 'numpy.ndarray'>
print(psalms["glove_tfidf_vec"].iloc[0].shape)  # e.g., (300,)

<class 'numpy.ndarray'>
(100,)

In [17]:
import numpy as np

for word in glove_vectors:
    glove_vectors[word] = np.array(glove_vectors[word], dtype=float)

In [18]:
#glove_vectors

In [19]:
compute_query_embedding('deliverance')

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
import pandas as pd
import numpy as np

def query_tfidf_glove(query, top_k=5):

    q_vec = compute_query_embedding(query)
    if q_vec is None:
        return pd.DataFrame()

    q_vec = np.asarray(q_vec, dtype=float)
    q_norm = np.linalg.norm(q_vec)

    sims = []

    for idx, row in psalms.iterrows():

        doc_vec = row['glove_tfidf_vec']

        # robust parsing
        if isinstance(doc_vec, str):
            doc_vec = (
                doc_vec.replace("[", "")
                       .replace("]", "")
                       .replace(",", " ")
            )
            doc_vec = np.fromstring(doc_vec, sep=" ")

        doc_vec = np.asarray(doc_vec, dtype=float)

        if len(doc_vec) == 0 or q_norm == 0:
            continue

        if len(doc_vec) != len(q_vec):
            continue

        doc_norm = np.linalg.norm(doc_vec)
        if doc_norm == 0:
            continue

        sim = np.dot(q_vec, doc_vec) / (q_norm * doc_norm)
        sims.append((idx, sim))

    sims.sort(key=lambda x: x[1], reverse=True)
    top = sims[:top_k]
    
    print("number of valid matches:", len(sims))
    
    return pd.DataFrame({
        "Method": ["TF-IDF + GloVe"] * len(top),
        "Similarity Score (%)": [round(s[1] * 100, 2) for s in top],
        "Text": [psalms.loc[i, "text"] for i, _ in top],
        "Psalm Num": [psalms.loc[i, "psalm_num"] for i, _ in top],
        "Verse": [psalms.loc[i, "verse"] for i, _ in top],
    })
query = "For the Peace of the World"

(query_tfidf_glove(query))

number of valid matches: 301

,Method,Similarity Score (%),Text,Psalm Num,Verse
0,TF-IDF + GloVe,16.00,Bible,79,1For the End concerning things that shall be c...
1,TF-IDF + GloVe,13.98,Bible,122,1An ode of ascents Ilift my eyes to You Whodwe...
2,TF-IDF + GloVe,13.46,Bible,56,1For the End corrupt not by David for a pillar...
3,TF-IDF + GloVe,13.11,Bible,119,An ode of ascents To the Lord in my affliction...
4,TF-IDF + GloVe,12.74,Bible,11,For the End concerning the eighth a psalm by D...

In [21]:
print(psalms.columns.tolist())

['Unnamed: 0', 'tradition', 'text', 'psalm_num', 'verse', 'cleaned_verse', 'glove_tfidf_vec', 'glove']

## Testing

In [22]:
query = "For the Peace of the World"

query_tfidf_glove('Forgivness')

number of valid matches: 0

Empty DataFrame
Columns: [Method, Similarity Score (%), Text, Psalm Num, Verse]
Index: []

# BERT & SBERT

## BERT

In [23]:
import torch
from transformers import AutoTokenizer, AutoModel
from sentence_transformers import SentenceTransformer

In [24]:
sbert_model = SentenceTransformer("all-mpnet-base-v2")
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
bert_model = AutoModel.from_pretrained("bert-base-uncased")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: bert-base-uncased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [25]:
print(os.getcwd())
output_dir = "../data/bert"
psalm_embeddings = []

# Load all saved embeddings
for filename in sorted(os.listdir(output_dir)):
    if filename.endswith(".npy") and "psalm_" in filename:
        emb = np.load(os.path.join(output_dir, filename))
        psalm_embeddings.append(emb)

psalm_embeddings = np.stack(psalm_embeddings)  # shape: (num_psalms, 768)
print("Loaded psalm embeddings:", psalm_embeddings.shape)

/opt/notebooks/psalms_nlp_sp26/query_compare
Loaded psalm embeddings: (301, 768)

%pip install --upgrade torch transformers sentence-transformers huggingface_hub

In [26]:
# --- Clean Psalm Encoder using BERT ---
from transformers import AutoTokenizer, AutoModel
import torch
import numpy as np

# 1️⃣ Set device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

# 2️⃣ Load tokenizer and model (fresh instances)
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased", use_fast=True)
bert_model = AutoModel.from_pretrained("bert-base-uncased").to(device)
bert_model.eval()  # evaluation mode

Using device: cpu

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: bert-base-uncased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(30522, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0-11): 12 x BertLayer(
        (attention): BertAttention(
          (self): BertSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
        (intermediate): BertIntermediate(
          (dense): Linear(in_features=768, out_features=3072, bias=True)
          (intermediate_act_fn): GELUActivation()
        )
        (output): BertOutput(
          (dense): Linear(in_features=3072, out_features=768, bias=True)
          (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
    )
  )
  (pooler): BertPooler(
    (dense): Linear(in_features=768, out_features=768, bias=True)
    (activation): Tanh()
  )
)

In [27]:
def encode_text_bert(text: str) -> np.ndarray:
    """
    Encode a single text string into a 1D numpy array (hidden_size,)
    Uses attention-mask weighted mean to ignore padding.
    """
    # Tokenize
    inputs = tokenizer(
        text,
        return_tensors="pt",
        padding=True,
        truncation=True,
        max_length=512
    )
    
    # Move inputs to device
    inputs = {k: v.to(device) for k, v in inputs.items()}
    
    with torch.no_grad():
        outputs = bert_model(**inputs)  # last_hidden_state: (1, seq_len, hidden)
        hidden = outputs.last_hidden_state
        mask = inputs.get("attention_mask")
        
        if mask is None:
            pooled = hidden.mean(dim=1)
        else:
            mask = mask.unsqueeze(-1)  # (1, seq_len, 1)
            masked_hidden = hidden * mask
            summed = masked_hidden.sum(dim=1)
            counts = mask.sum(dim=1).clamp(min=1e-9)
            pooled = summed / counts
    
    return pooled.squeeze(0).cpu().numpy()

In [28]:
def cosine_similarity(a: np.ndarray, b: np.ndarray) -> float:
    """Compute cosine similarity between two 1D numpy arrays."""
    a_norm = a / np.linalg.norm(a)
    b_norm = b / np.linalg.norm(b)
    return float(np.dot(a_norm, b_norm))

In [29]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

def query_bert(query, top_k=5):

    print("BERT Query:", query)

    if not query:
        print("Empty query. Exiting.")
        return pd.DataFrame()

    # 1. Encode query
    query_emb = encode_text_bert(query)

    similarities = []

    # 2. Compute similarities safely
    for i, psalm_emb in enumerate(psalm_embeddings):

        sim = cosine_similarity(
            query_emb.reshape(1, -1),
            psalm_emb.reshape(1, -1)
        )[0][0]

        similarities.append((i, sim))

    # 3. Sort
    similarities.sort(key=lambda x: x[1], reverse=True)
    top = similarities[:top_k]

    # 4. Build DataFrame (IMPORTANT: consistent schema)
    return pd.DataFrame({
        "Method": ["BERT"] * len(top),
        "Similarity Score (%)": [round(s[1] * 100, 2) for s in top],
        "Text": [psalms.loc[i, "text"] for i, _ in top],
        "Psalm Num": [psalms.loc[i, "psalm_num"] for i, _ in top],
        "Verse": [psalms.loc[i, "verse"] for i, _ in top],
    })

## Testing

In [30]:
(query_bert("Create in me a clean heart"))

BERT Query: Create in me a clean heart

,Method,Similarity Score (%),Text,Psalm Num,Verse
0,BERT,69.89,Bible,18,For the End a psalm by David The heavens decla...
1,BERT,69.06,Psalter,34,"Judge Thou, O Lord, them that do me injustice;..."
2,BERT,68.69,Psalter,49,"The God of gods, even the Lord, hath spoken, a..."
3,BERT,68.66,Psalter,43,"We have heard with our ears, O God, for our fa..."
4,BERT,68.31,Bible,147,Alleluia of Aggeus and Zacharias Praise the Lo...

## SBERT

%pip install --upgrade torch transformers sentence-transformers datasets huggingface_hub

%pip install --upgrade torch transformers sentence-transformers datasets huggingface_hub

import torch
from transformers import AutoTokenizer, AutoModel
from sentence_transformers import SentenceTransformer

# Load models
sbert_model = SentenceTransformer("all-mpnet-base-v2")
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
bert_model = AutoModel.from_pretrained("bert-base-uncased")

In [31]:
output_dir = "../data/sbert"
psalm_SBERT_embeddings = []

# Load all saved embeddings
for filename in sorted(os.listdir(output_dir)):
    if filename.endswith(".npy") and "psalm_" in filename:
        emb = np.load(os.path.join(output_dir, filename))
        psalm_SBERT_embeddings.append(emb)

psalm_SBERT_embeddings = np.stack(psalm_SBERT_embeddings)  # shape: (num_psalms, 768)
print("Loaded psalm embeddings:", psalm_SBERT_embeddings.shape)

Loaded psalm embeddings: (301, 768)

In [32]:
def encode_text_SBERT(text):
    return sbert_model.encode(text, convert_to_numpy=True)

In [33]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

def query_sbert(query, top_k=5):

    print("Query:", query)

    if not query:
        print("Empty query. Exiting.")
        return pd.DataFrame()

    query_emb = encode_text_SBERT(query)

    similarities = []

    for i, psalm_emb in enumerate(psalm_SBERT_embeddings):

        sim = cosine_similarity(
            query_emb.reshape(1, -1),
            psalm_emb.reshape(1, -1)
        )[0][0]

        similarities.append((i, sim))

    # correct sorting
    similarities.sort(key=lambda x: x[1], reverse=True)
    top = similarities[:top_k]

    return pd.DataFrame({
        "Method": ["SBERT"] * len(top),
        "Similarity Score (%)": [round(s[1] * 100, 2) for s in top],
        "Text": [psalms.loc[i, "text"] for i, _ in top],
        "Psalm Num": [psalms.loc[i, "psalm_num"] for i, _ in top],
        "Verse": [psalms.loc[i, "verse"] for i, _ in top],
    })

## Testing

In [34]:
query_sbert(query)

Query: For the Peace of the World

,Method,Similarity Score (%),Text,Psalm Num,Verse
0,SBERT,34.36,Psalter,85,"Bow down Thine ear, O Lord, and hear me, for I..."
1,SBERT,34.26,Psalter,34,"Judge Thou, O Lord, them that do me injustice;..."
2,SBERT,33.66,Bible,12,For the End a psalm by David How long O Lord W...
3,SBERT,33.61,Bible,136,By David By the rivers of Babylon There we sat...
4,SBERT,33.56,Psalter,16,"Hear my right, O Lord; attend unto my supplica..."

#### Comparing Embedding sizes

I am getting very low similarity percentages for `SBERT` results compared to `BERT` results. There are a few things that may be contributing to this. One of them may have to do with the different dimensions of embeddings between `BERT` & `SBERT`. Let look at that first.

In [35]:
print(f"BERT Embeddings: {psalm_embeddings.shape}")
print(f"SBERT Embeddings: {psalm_SBERT_embeddings.shape}")

BERT Embeddings: (301, 768)
SBERT Embeddings: (301, 768)

The dimensions for both are the same, therefore the problems seems like i t lies within the `SBERT` algorithm itself. Lets look at the embeddings for `SBERT` closer and see what is happening. We are going to look at the embeddings right before the cosine similarity is calculated and see if there are any negatives within the embeddings.

In [36]:
def query_sbert(query, top_k=5):
    print("Query: ", query)

    if not query:
        print("Empty query. Exiting.")
        return
    
    query_emb = encode_text_SBERT(query)

    similarities = []

    for i, psalm_emb in enumerate(psalm_SBERT_embeddings):
        print(f"Query: {query_emb} \n Emedding: {psalm_emb}")
        sim = cosine_similarity(query_emb, psalm_emb)
        similarities.append((i, round(sim*100, 2)))

    
    # 3. Sort by similarity descending
    sims = sorted(similarities, reverse=True)[:5]
    

    # Return the top_k indices
    top_indices = [("SBERT", idx,sim) for idx, sim in sims[:top_k]]

    # Checking the Output
    print(top_indices)

In [37]:
# query_sbert(query)

It can be seen that there are negative values within the embeddings and because of this it is interfereing with the score and making them seem lower than they actually are. We can write a simple sunction to basically shift all of the embedding to be strictly **positive**, which should fix the off balance of similarity scores.

In [38]:
def shift_embedding(embedding):
    min_val = embedding.min()
    shifted = embedding - min_val

    return shifted

We can now apply this to the embeddings themselves and then look at the similarities again and see if this affected the similarities.

In [39]:
psalm_SBERT_embeddings = shift_embedding(psalm_SBERT_embeddings)

In [40]:
def query_sbert(query, top_k=5):
    print("Query: ", query)

    if not query:
        print("Empty query. Exiting.")
        return
    
    query_emb = encode_text_SBERT(query)

    similarities = []

    # Shifting the Embeddings
    query_emb = shift_embedding(query_emb)
    #psalm_SBERT_embeddings = shift_embedding(psalm_SBERT_embeddings)

    for i, psalm_emb in enumerate(psalm_SBERT_embeddings):
        print(f"Query: {query_emb} \n Emedding: {psalm_emb}")
        sim = cosine_similarity(query_emb, psalm_emb)
        similarities.append((i, round(sim*100, 2)))

    
    # 3. Sort by similarity descending
    sims = sorted(similarities, reverse=True)[:5]
    

    # Return the top_k indices
    top_indices = [("SBERT", idx,sim) for idx, sim in sims[:top_k]]

    # Checking the Output
    print(top_indices)

Let's run the same query again and see if there are different results given.

In [41]:
query_sbert("Create in me a Clean Heart")

Query:  Create in me a Clean Heart
Query: [0.144041   0.16391128 0.11957268 0.11398134 0.16161565 0.12547918
 0.01388347 0.09307168 0.15530768 0.14702438 0.15252075 0.0992409
 0.1392225  0.18021789 0.13122708 0.08671212 0.15452042 0.16285303
 0.15117484 0.13216761 0.12792727 0.1305647  0.18125588 0.11342865
 0.18147168 0.08616063 0.13341296 0.13963069 0.06126743 0.09915967
 0.10519531 0.1155621  0.10027812 0.08963308 0.12723507 0.09206307
 0.12562008 0.08981759 0.08822752 0.09504876 0.07952172 0.054586
 0.15622061 0.15511979 0.10312023 0.1866107  0.11647746 0.17881031
 0.17074336 0.16453783 0.09811521 0.15076812 0.08721405 0.10297816
 0.18135694 0.21840815 0.08564647 0.10740616 0.09267608 0.12205959
 0.09855492 0.18401468 0.13648963 0.1667794  0.25000256 0.11757109
 0.19473204 0.10739695 0.13103506 0.09265086 0.10427506 0.11635843
 0.1431204  0.17826474 0.10959605 0.0016821  0.1351851  0.13314775
 0.15238702 0.17256722 0.13048959 0.09072299 0.15148053 0.11148529
 0.1352602  0.04742495 0.13125423 0.10740409 0.19568834 0.1544445
 0.05637647 0.08608235 0.0846107  0.11884604 0.12654638 0.12697752
 0.12276372 0.11839684 0.11432299 0.13752195 0.13701324 0.12959588
 0.15004826 0.11136013 0.10596737 0.03538759 0.15088946 0.17922448
 0.08898596 0.14011975 0.1393435  0.12839757 0.12891072 0.1464208
 0.11116003 0.1661249  0.04128021 0.11516858 0.10751072 0.09913867
 0.12919694 0.11439744 0.14353667 0.1469236  0.13996953 0.10243148
 0.12326317 0.11629283 0.08375002 0.09314804 0.13248259 0.10974549
 0.12297926 0.13620849 0.14906572 0.10554168 0.09196539 0.1494464
 0.09010443 0.12852642 0.12460956 0.12940745 0.1571509  0.13242976
 0.10974956 0.07412701 0.17018902 0.09254252 0.12450959 0.1247798
 0.0986635  0.13731167 0.0819943  0.14852102 0.13586031 0.1860641
 0.12646805 0.09959739 0.11250486 0.11847523 0.13199311 0.12464609
 0.12973897 0.14030749 0.16250165 0.12062672 0.13824767 0.08065422
 0.11009768 0.14511685 0.10667896 0.11011709 0.09773145 0.1511995
 0.14615855 0.15384504 0.15561958 0.12457398 0.0748879  0.08119357
 0.11577217 0.05015905 0.08457692 0.11875659 0.18656439 0.16425355
 0.13003935 0.17502853 0.09994943 0.14423303 0.12796341 0.09571782
 0.10241003 0.09378565 0.13261315 0.14527422 0.13325952 0.1145611
 0.17241682 0.06200293 0.11743188 0.09942354 0.22549325 0.14675656
 0.13471611 0.14894353 0.14282109 0.09254086 0.12173131 0.1064005
 0.10470998 0.15368022 0.1499884  0.11276153 0.09941389 0.16752619
 0.09405212 0.12802242 0.13144583 0.13325176 0.09675396 0.18778387
 0.15241612 0.12520373 0.15512107 0.15230127 0.12081923 0.1574138
 0.17639597 0.14067104 0.15039963 0.12118118 0.16801336 0.12158179
 0.11593558 0.11536038 0.11780947 0.1244451  0.11589947 0.03948625
 0.11406469 0.15866423 0.14902563 0.12841833 0.0797423  0.17290728
 0.13651758 0.1033449  0.12407842 0.10389177 0.1017867  0.15661472
 0.0862716  0.07923313 0.13847736 0.09311122 0.08706959 0.13389854
 0.14745116 0.10721953 0.07402769 0.09270532 0.14106703 0.15373354
 0.2079114  0.12781537 0.134773   0.10300428 0.10380454 0.12560868
 0.09789804 0.12069276 0.20093894 0.10471838 0.12709105 0.10438935
 0.17060204 0.17948052 0.15557435 0.13239937 0.1213607  0.17389376
 0.14407393 0.17551816 0.11953396 0.1422266  0.14771399 0.15302819
 0.16125377 0.1466179  0.15301046 0.15627187 0.16463585 0.0829076
 0.12505469 0.09661679 0.04948406 0.15224798 0.11727181 0.1159986
 0.06714204 0.18673663 0.14417508 0.13351704 0.16529731 0.11400716
 0.16102569 0.09999342 0.17141111 0.15963265 0.14064264 0.11438295
 0.11024756 0.14857483 0.14767295 0.09877318 0.08009557 0.06963187
 0.15148716 0.13453524 0.08931336 0.10358614 0.07912725 0.138652
 0.1684093  0.14051256 0.19291717 0.17651917 0.14635101 0.05945259
 0.15182628 0.16536744 0.1342093  0.12415916 0.11991897 0.0727637
 0.10995988 0.1567154  0.10672785 0.12105259 0.11191978 0.13325873
 0.11405838 0.14212415 0.07818854 0.09426273 0.1777815  0.21484783
 0.19428186 0.10432385 0.0973475  0.12394063 0.17449816 0.10554622
 0.13832267 0.08854696 0.11954531 0.11977924 0.15066941 0.11406159
 0.14656758 0.14966792 0.21433221 0.12348574 0.12287222 0.12415464
 0.11841206 0.17116666 0.11221544 0.04515461 0.10803807 0.17337319
 0.1502402  0.16046232 0.11850757 0.19543467 0.15036474 0.10264108
 0.1085124  0.13058788 0.13650146 0.06438206 0.12154187 0.13778542
 0.06976804 0.094459   0.11837341 0.15332854 0.10642727 0.12574187
 0.1682004  0.17207265 0.02615964 0.14700356 0.10408794 0.11120173
 0.1651099  0.14050704 0.15731066 0.14485057 0.10581034 0.2514482
 0.15649344 0.154199   0.13287461 0.13756748 0.12016567 0.16078106
 0.15068497 0.12147843 0.06514165 0.22431403 0.1423747  0.14578223
 0.14017557 0.16161267 0.10775863 0.09901463 0.16192167 0.02221249
 0.10477392 0.13668877 0.16028126 0.19504878 0.14142229 0.1795374
 0.14097211 0.12036309 0.1663232  0.10416929 0.13130276 0.18727373
 0.12017883 0.18254559 0.1033488  0.0420711  0.11922725 0.03016349
 0.14177975 0.06146163 0.0944605  0.1041651  0.19039962 0.19586357
 0.12122447 0.1797039  0.10032576 0.11168854 0.10923579 0.04659316
 0.1504252  0.15022282 0.09845795 0.16250546 0.14838892 0.13098253
 0.15762949 0.15590012 0.15308054 0.15483636 0.19075672 0.15160893
 0.11938156 0.1146122  0.16421361 0.13935095 0.02116947 0.04181691
 0.14045386 0.11342835 0.13399516 0.12074601 0.12212768 0.14981216
 0.11913096 0.13865848 0.10551687 0.14863412 0.1003537  0.11929832
 0.1748968  0.10497502 0.10325342 0.14061107 0.10548259 0.11902952
 0.17899895 0.11975497 0.1227681  0.1719702  0.13296324 0.1527972
 0.10916836 0.05309713 0.09688948 0.06139926 0.10084741 0.05034716
 0.10780726 0.15031673 0.14722863 0.14957318 0.15558857 0.15635289
 0.15637134 0.10481589 0.10654581 0.13051479 0.12659223 0.12525305
 0.12406856 0.09057076 0.12405393 0.13632219 0.1146832  0.12848526
 0.12624086 0.08836777 0.10690258 0.14410308 0.12366311 0.1311831
 0.111798   0.13054645 0.1399822  0.11113822 0.08618732 0.14611705
 0.06040096 0.149429   0.         0.18566415 0.1581849  0.12944318
 0.07967665 0.21056962 0.15607315 0.13851519 0.11921671 0.14493226
 0.11375856 0.1121859  0.20378095 0.13817059 0.12301282 0.09883215
 0.14875364 0.13400336 0.11910875 0.14841697 0.1280694  0.17970324
 0.06553056 0.10497924 0.13934903 0.12723337 0.10878649 0.17644277
 0.12477564 0.08322996 0.06948854 0.1009403  0.1135374  0.12066556
 0.13345866 0.15912724 0.11769099 0.13431218 0.14113921 0.09457822
 0.20110333 0.11344809 0.17722312 0.1381649  0.11485819 0.11910639
 0.1000935  0.1268384  0.12537704 0.1368081  0.05932555 0.14866954
 0.09055701 0.17627266 0.14850232 0.1038089  0.1130814  0.14259554
 0.15036589 0.13287403 0.12392177 0.19093406 0.08796145 0.10412295
 0.14192282 0.1078187  0.08456708 0.06056958 0.08041279 0.11070582
 0.13404274 0.0983322  0.1404881  0.14094946 0.12522665 0.05323122
 0.10778685 0.08140737 0.11656877 0.02525208 0.07044017 0.04866485
 0.11729054 0.17297539 0.14096178 0.14478612 0.17170544 0.12752178
 0.07531886 0.14201903 0.10162286 0.12731017 0.15158704 0.11413722
 0.16152577 0.19867192 0.14145029 0.12191311 0.10353033 0.15843849
 0.06889845 0.05882657 0.11764632 0.16066124 0.08054227 0.14803168
 0.11320507 0.16043624 0.19885123 0.16352957 0.10430237 0.03944552
 0.12891215 0.19222224 0.10915647 0.16742688 0.1128054  0.0835845
 0.14541706 0.11927255 0.16048537 0.09343883 0.17112927 0.09928641
 0.1167801  0.09792987 0.19039208 0.12440899 0.16284046 0.14539364
 0.16912754 0.15018898 0.16758655 0.0973464  0.08043073 0.12052716
 0.08441727 0.19371466 0.13100341 0.07061285 0.07313204 0.157463
 0.14123942 0.07273811 0.10707119 0.11807501 0.11573991 0.15309443
 0.15907729 0.14059034 0.14518553 0.13620016 0.13770421 0.1741237
 0.21988767 0.07053508 0.11674759 0.11569695 0.12723361 0.07696804
 0.07956757 0.13588813 0.08095998 0.12352368 0.1949324  0.1123224
 0.11896874 0.04049236 0.09173934 0.13102654 0.11672974 0.12126014
 0.08351004 0.12111515 0.17522544 0.14659077 0.08296033 0.1513844
 0.11659167 0.13962138 0.14408717 0.13425753 0.08852738 0.16009113
 0.2557649  0.15078692 0.08502984 0.08823878 0.1700638  0.10235827
 0.10530815 0.13351703 0.06881453 0.1172892  0.06808269 0.18704717
 0.22933735 0.13769613 0.17381623 0.09508312 0.18435706 0.11324972
 0.16299525 0.09266131 0.12375241 0.13678615 0.09963081 0.10127085
 0.15252998 0.11751616 0.15093419 0.10323996 0.14931267 0.11495364
 0.14399855 0.12605329 0.13041852 0.14378643 0.10442729 0.15744823
 0.14268498 0.15786862 0.16805764 0.12298524 0.07058505 0.11158643
 0.12723337 0.14604446 0.06310107 0.14268887 0.13383362 0.1724954
 0.13294062 0.12999474 0.13919947 0.09872483 0.16160148 0.14653651]
 Emedding: [0.16520211 0.18811554 0.18127804 0.16327658 0.17499168 0.22485775
 0.18755026 0.20347838 0.2149091  0.15735567 0.18174979 0.20864971
 0.17817125 0.08346275 0.2367028  0.12844887 0.1651749  0.22956368
 0.18042035 0.20562682 0.18734644 0.18479247 0.20856957 0.20241882
 0.25115326 0.15459408 0.17818068 0.21995553 0.18214089 0.1342138
 0.16118565 0.17445065 0.19762237 0.21927682 0.18075557 0.19201584
 0.2502708  0.16756809 0.1341812  0.19638947 0.13678008 0.1654631
 0.16768016 0.19816288 0.16832371 0.10845609 0.14290954 0.20557655
 0.18270676 0.19218099 0.20598114 0.18474072 0.19390628 0.18681063
 0.24902116 0.22931801 0.18966627 0.14692628 0.07806349 0.20349036
 0.1628501  0.17205445 0.15326187 0.185404   0.1870692  0.15857628
 0.21976005 0.2182437  0.17672087 0.16384533 0.17979164 0.16438505
 0.19858815 0.21689078 0.16086873 0.12233748 0.20970711 0.20838737
 0.1661384  0.15083945 0.19904345 0.13562642 0.15942702 0.12900959
 0.18258752 0.15756835 0.192008   0.18462512 0.21666327 0.17218469
 0.14292853 0.16414526 0.10196745 0.1382672  0.229748   0.1764119
 0.15287307 0.1771072  0.16755837 0.15715806 0.2196411  0.1680879
 0.17849365 0.19705349 0.14475316 0.14739066 0.2811383  0.23727995
 0.1758067  0.20770055 0.21117218 0.24188754 0.17391297 0.18144533
 0.15382965 0.19359165 0.17504163 0.19485185 0.16576962 0.18576558
 0.13265525 0.16286434 0.19759351 0.18318272 0.20841654 0.1255647
 0.18810064 0.15787476 0.15831664 0.13342398 0.1913075  0.18120678
 0.16113433 0.221993   0.18704917 0.26131016 0.23178    0.14072508
 0.1612508  0.19816446 0.15575722 0.22401458 0.17003864 0.20403115
 0.17039798 0.2120208  0.15686098 0.14177805 0.19259576 0.21137413
 0.18124154 0.18296666 0.18680617 0.17393059 0.14504968 0.16677652
 0.13268843 0.15262616 0.13922979 0.17984076 0.20491888 0.19205572
 0.18647243 0.1941141  0.23041958 0.20755363 0.17489572 0.1438957
 0.2286778  0.12873733 0.15021661 0.16384515 0.17089733 0.2184525
 0.1934479  0.17753659 0.23495318 0.13997146 0.13530678 0.19735324
 0.19492339 0.17396206 0.16601543 0.17566971 0.21546529 0.1750175
 0.18869236 0.1849634  0.16944627 0.20203032 0.13696025 0.21047263
 0.04137327 0.17345867 0.14997448 0.20288229 0.1556224  0.19627969
 0.23789042 0.14803046 0.18055648 0.23062935 0.2195455  0.16579548
 0.2167134  0.21259159 0.2038904  0.14179958 0.20392814 0.1948615
 0.13404547 0.20767973 0.14517272 0.17530406 0.16586657 0.22109757
 0.17565386 0.21395463 0.072455   0.16064169 0.2028391  0.15267147
 0.13339864 0.20028937 0.23525907 0.17091733 0.12487084 0.20635499
 0.19384636 0.15196809 0.17241171 0.14617483 0.19751589 0.15534016
 0.15902403 0.20559195 0.17409842 0.13837029 0.20360555 0.03124784
 0.14858028 0.21050745 0.20576689 0.17399764 0.20662475 0.13979214
 0.16317622 0.14558157 0.16939706 0.1447561  0.17588194 0.18632522
 0.1910485  0.20280288 0.19623506 0.12503606 0.1843235  0.19478494
 0.36159527 0.09213632 0.13853565 0.14807925 0.12262748 0.16943593
 0.16583978 0.19288188 0.18808404 0.17453425 0.19886738 0.19402272
 0.17938806 0.22088587 0.19778198 0.22428787 0.18624738 0.16847037
 0.2285253  0.17246127 0.14552158 0.17806575 0.13076505 0.17409158
 0.16264032 0.22866821 0.12724066 0.21243769 0.1784886  0.2051206
 0.17107171 0.22544797 0.17568837 0.20989169 0.18982993 0.18575312
 0.1835027  0.19075863 0.17538165 0.18380637 0.21815652 0.21246949
 0.13558663 0.2317508  0.1936545  0.17652862 0.21761557 0.15398395
 0.19774437 0.1384211  0.12951465 0.19413352 0.24139667 0.15170445
 0.15026121 0.25060752 0.17685916 0.20511845 0.13132262 0.16033302
 0.19861409 0.12370229 0.1923614  0.10563783 0.17402934 0.20504862
 0.18998694 0.22466019 0.2694411  0.18350554 0.23664612 0.2056097
 0.16174296 0.09736394 0.16491018 0.1731468  0.16794921 0.20884928
 0.21972843 0.28089875 0.15348727 0.18383028 0.18045923 0.14785522
 0.19741617 0.18360858 0.18186773 0.15398604 0.25437105 0.2470763
 0.17186207 0.16975906 0.15577173 0.16338143 0.17237332 0.18050009
 0.16978614 0.11296298 0.15931752 0.15721238 0.16574447 0.18060951
 0.19552483 0.09504787 0.21624145 0.2285091  0.15815733 0.20592344
 0.19849552 0.21254027 0.1934963  0.18561934 0.11876401 0.20488206
 0.2510643  0.21863957 0.19826064 0.15280516 0.1971915  0.11837904
 0.13642165 0.19407952 0.20543665 0.14032696 0.1629179  0.16228795
 0.16421543 0.18268566 0.1773791  0.25126576 0.17323574 0.2081728
 0.20153873 0.2772141  0.14029208 0.21489637 0.18796971 0.18709655
 0.14999066 0.22110406 0.19436696 0.19767314 0.17465535 0.21938705
 0.2891714  0.19355078 0.14144753 0.26873857 0.2119936  0.23447835
 0.1655865  0.20744699 0.0746441  0.16634189 0.18006143 0.20399638
 0.17297639 0.24261375 0.1617835  0.19912753 0.17485604 0.13739082
 0.2077971  0.22072461 0.20567782 0.17081049 0.18657583 0.23605198
 0.2141353  0.18215215 0.18680537 0.19562347 0.23076767 0.16582407
 0.14821959 0.1393726  0.13354519 0.18046111 0.23146379 0.23418364
 0.14696516 0.14615035 0.18637331 0.13581182 0.22022079 0.25881115
 0.11730679 0.19426027 0.13413571 0.18231004 0.12133202 0.21628205
 0.20473547 0.20284918 0.16634594 0.1995988  0.14223744 0.1500921
 0.20663653 0.22286381 0.177391   0.25860935 0.2224178  0.19397749
 0.20582663 0.14582486 0.20065416 0.17773391 0.11177301 0.21704072
 0.25446653 0.17042121 0.14284058 0.20185417 0.17143936 0.1926105
 0.18364409 0.23911905 0.147414   0.27735656 0.16635476 0.18440376
 0.13419224 0.20587973 0.21077886 0.10085653 0.15862904 0.17660819
 0.22183032 0.15893628 0.19902338 0.22462514 0.18946889 0.1755825
 0.1679245  0.23957258 0.18799244 0.13084653 0.16682348 0.2334448
 0.18767472 0.16302362 0.13438761 0.16516109 0.18663473 0.21743175
 0.19891419 0.19979441 0.16432267 0.15896335 0.18126766 0.16834347
 0.18075778 0.15670422 0.14727524 0.13012421 0.16644597 0.09690741
 0.14624144 0.21134993 0.15867698 0.18963729 0.18508849 0.16631742
 0.1665743  0.13729507 0.19198777 0.17550977 0.15268081 0.20329861
 0.16214275 0.2096878  0.1275037  0.22511959 0.19562948 0.17183517
 0.17215864 0.18783084 0.25894883 0.13297573 0.176483   0.21582414
 0.17706183 0.22514942 0.21203402 0.16817555 0.18889818 0.16202475
 0.18276304 0.23346584 0.16131884 0.16847746 0.11418701 0.23991291
 0.1267589  0.19155781 0.17815423 0.1807533  0.11755873 0.20188312
 0.1961735  0.15525976 0.14400566 0.15838301 0.18841818 0.18642253
 0.1733316  0.18647224 0.17436334 0.22427492 0.18192722 0.16113359
 0.26392174 0.13945359 0.17046808 0.20370047 0.2185921  0.17899337
 0.19696034 0.21105066 0.18863893 0.21636602 0.18677376 0.22586724
 0.16655713 0.10914471 0.23809259 0.17042223 0.17351231 0.19435148
 0.16065775 0.1558026  0.2153028  0.1705742  0.19050272 0.18562073
 0.19634224 0.16958964 0.11592777 0.20927346 0.10064711 0.16922897
 0.13341966 0.16816837 0.21815306 0.23817529 0.14100516 0.16679452
 0.08526137 0.18314402 0.15017025 0.09532203 0.06454791 0.15939294
 0.20710856 0.25734818 0.08470344 0.17103305 0.20306504 0.16845375
 0.113956   0.22106205 0.18162237 0.24220309 0.20272014 0.15818879
 0.18674543 0.2045809  0.2000894  0.14849544 0.17987958 0.12952337
 0.11475497 0.15219842 0.17058292 0.20337568 0.16022962 0.19560233
 0.22740483 0.19507475 0.16121706 0.17439699 0.15613557 0.04313172
 0.17974012 0.24809003 0.19021727 0.1834625  0.22801986 0.17072524
 0.18770106 0.15451083 0.22641672 0.2046767  0.16341054 0.16549279
 0.1663439  0.18566279 0.19518118 0.13269943 0.20839822 0.21222462
 0.18281443 0.19485451 0.20977442 0.16246592 0.14617717 0.1285167
 0.13673729 0.17845508 0.18687996 0.16042738 0.16105616 0.18499552
 0.17093454 0.13585344 0.16055892 0.10291418 0.22338936 0.25689662
 0.17840825 0.1603103  0.16702572 0.16127534 0.2031256  0.18439351
 0.17915389 0.09883469 0.19423044 0.17614618 0.18075359 0.18077466
 0.18296216 0.17865545 0.19618903 0.19208792 0.24332207 0.19779173
 0.21287864 0.1420003  0.1738983  0.16227552 0.14968136 0.20142013
 0.13565832 0.15750584 0.19421086 0.1963142  0.1346146  0.1869582
 0.19105007 0.21955922 0.20638768 0.15017858 0.16857415 0.2021909
 0.22434005 0.1716003  0.18590593 0.17340218 0.19277081 0.12762612
 0.16999544 0.17775406 0.18130386 0.14986937 0.1567638  0.20221567
 0.19415015 0.15683696 0.19806613 0.18835533 0.13718805 0.16394535
 0.1851192  0.17068101 0.20367967 0.1755907  0.27029866 0.23621038
 0.22469686 0.13289465 0.23531519 0.14608729 0.14906013 0.17893346
 0.12467325 0.20346746 0.18311109 0.20080839 0.19768707 0.20460354
 0.17219126 0.20452243 0.24981657 0.17211832 0.1950301  0.18327527
 0.1807533  0.21347484 0.12780052 0.18594407 0.16149727 0.18585935
 0.1630035  0.1629622  0.15953724 0.16213335 0.18515162 0.16021152]

ValueError: Expected 2D array, got 1D array instead:
array=[0.144041   0.16391128 0.11957268 0.11398134 0.16161565 0.12547918
 0.01388347 0.09307168 0.15530768 0.14702438 0.15252075 0.0992409
 0.1392225  0.18021789 0.13122708 0.08671212 0.15452042 0.16285303
 0.15117484 0.13216761 0.12792727 0.1305647  0.18125588 0.11342865
 0.18147168 0.08616063 0.13341296 0.13963069 0.06126743 0.09915967
 0.10519531 0.1155621  0.10027812 0.08963308 0.12723507 0.09206307
 0.12562008 0.08981759 0.08822752 0.09504876 0.07952172 0.054586
 0.15622061 0.15511979 0.10312023 0.1866107  0.11647746 0.17881031
 0.17074336 0.16453783 0.09811521 0.15076812 0.08721405 0.10297816
 0.18135694 0.21840815 0.08564647 0.10740616 0.09267608 0.12205959
 0.09855492 0.18401468 0.13648963 0.1667794  0.25000256 0.11757109
 0.19473204 0.10739695 0.13103506 0.09265086 0.10427506 0.11635843
 0.1431204  0.17826474 0.10959605 0.0016821  0.1351851  0.13314775
 0.15238702 0.17256722 0.13048959 0.09072299 0.15148053 0.11148529
 0.1352602  0.04742495 0.13125423 0.10740409 0.19568834 0.1544445
 0.05637647 0.08608235 0.0846107  0.11884604 0.12654638 0.12697752
 0.12276372 0.11839684 0.11432299 0.13752195 0.13701324 0.12959588
 0.15004826 0.11136013 0.10596737 0.03538759 0.15088946 0.17922448
 0.08898596 0.14011975 0.1393435  0.12839757 0.12891072 0.1464208
 0.11116003 0.1661249  0.04128021 0.11516858 0.10751072 0.09913867
 0.12919694 0.11439744 0.14353667 0.1469236  0.13996953 0.10243148
 0.12326317 0.11629283 0.08375002 0.09314804 0.13248259 0.10974549
 0.12297926 0.13620849 0.14906572 0.10554168 0.09196539 0.1494464
 0.09010443 0.12852642 0.12460956 0.12940745 0.1571509  0.13242976
 0.10974956 0.07412701 0.17018902 0.09254252 0.12450959 0.1247798
 0.0986635  0.13731167 0.0819943  0.14852102 0.13586031 0.1860641
 0.12646805 0.09959739 0.11250486 0.11847523 0.13199311 0.12464609
 0.12973897 0.14030749 0.16250165 0.12062672 0.13824767 0.08065422
 0.11009768 0.14511685 0.10667896 0.11011709 0.09773145 0.1511995
 0.14615855 0.15384504 0.15561958 0.12457398 0.0748879  0.08119357
 0.11577217 0.05015905 0.08457692 0.11875659 0.18656439 0.16425355
 0.13003935 0.17502853 0.09994943 0.14423303 0.12796341 0.09571782
 0.10241003 0.09378565 0.13261315 0.14527422 0.13325952 0.1145611
 0.17241682 0.06200293 0.11743188 0.09942354 0.22549325 0.14675656
 0.13471611 0.14894353 0.14282109 0.09254086 0.12173131 0.1064005
 0.10470998 0.15368022 0.1499884  0.11276153 0.09941389 0.16752619
 0.09405212 0.12802242 0.13144583 0.13325176 0.09675396 0.18778387
 0.15241612 0.12520373 0.15512107 0.15230127 0.12081923 0.1574138
 0.17639597 0.14067104 0.15039963 0.12118118 0.16801336 0.12158179
 0.11593558 0.11536038 0.11780947 0.1244451  0.11589947 0.03948625
 0.11406469 0.15866423 0.14902563 0.12841833 0.0797423  0.17290728
 0.13651758 0.1033449  0.12407842 0.10389177 0.1017867  0.15661472
 0.0862716  0.07923313 0.13847736 0.09311122 0.08706959 0.13389854
 0.14745116 0.10721953 0.07402769 0.09270532 0.14106703 0.15373354
 0.2079114  0.12781537 0.134773   0.10300428 0.10380454 0.12560868
 0.09789804 0.12069276 0.20093894 0.10471838 0.12709105 0.10438935
 0.17060204 0.17948052 0.15557435 0.13239937 0.1213607  0.17389376
 0.14407393 0.17551816 0.11953396 0.1422266  0.14771399 0.15302819
 0.16125377 0.1466179  0.15301046 0.15627187 0.16463585 0.0829076
 0.12505469 0.09661679 0.04948406 0.15224798 0.11727181 0.1159986
 0.06714204 0.18673663 0.14417508 0.13351704 0.16529731 0.11400716
 0.16102569 0.09999342 0.17141111 0.15963265 0.14064264 0.11438295
 0.11024756 0.14857483 0.14767295 0.09877318 0.08009557 0.06963187
 0.15148716 0.13453524 0.08931336 0.10358614 0.07912725 0.138652
 0.1684093  0.14051256 0.19291717 0.17651917 0.14635101 0.05945259
 0.15182628 0.16536744 0.1342093  0.12415916 0.11991897 0.0727637
 0.10995988 0.1567154  0.10672785 0.12105259 0.11191978 0.13325873
 0.11405838 0.14212415 0.07818854 0.09426273 0.1777815  0.21484783
 0.19428186 0.10432385 0.0973475  0.12394063 0.17449816 0.10554622
 0.13832267 0.08854696 0.11954531 0.11977924 0.15066941 0.11406159
 0.14656758 0.14966792 0.21433221 0.12348574 0.12287222 0.12415464
 0.11841206 0.17116666 0.11221544 0.04515461 0.10803807 0.17337319
 0.1502402  0.16046232 0.11850757 0.19543467 0.15036474 0.10264108
 0.1085124  0.13058788 0.13650146 0.06438206 0.12154187 0.13778542
 0.06976804 0.094459   0.11837341 0.15332854 0.10642727 0.12574187
 0.1682004  0.17207265 0.02615964 0.14700356 0.10408794 0.11120173
 0.1651099  0.14050704 0.15731066 0.14485057 0.10581034 0.2514482
 0.15649344 0.154199   0.13287461 0.13756748 0.12016567 0.16078106
 0.15068497 0.12147843 0.06514165 0.22431403 0.1423747  0.14578223
 0.14017557 0.16161267 0.10775863 0.09901463 0.16192167 0.02221249
 0.10477392 0.13668877 0.16028126 0.19504878 0.14142229 0.1795374
 0.14097211 0.12036309 0.1663232  0.10416929 0.13130276 0.18727373
 0.12017883 0.18254559 0.1033488  0.0420711  0.11922725 0.03016349
 0.14177975 0.06146163 0.0944605  0.1041651  0.19039962 0.19586357
 0.12122447 0.1797039  0.10032576 0.11168854 0.10923579 0.04659316
 0.1504252  0.15022282 0.09845795 0.16250546 0.14838892 0.13098253
 0.15762949 0.15590012 0.15308054 0.15483636 0.19075672 0.15160893
 0.11938156 0.1146122  0.16421361 0.13935095 0.02116947 0.04181691
 0.14045386 0.11342835 0.13399516 0.12074601 0.12212768 0.14981216
 0.11913096 0.13865848 0.10551687 0.14863412 0.1003537  0.11929832
 0.1748968  0.10497502 0.10325342 0.14061107 0.10548259 0.11902952
 0.17899895 0.11975497 0.1227681  0.1719702  0.13296324 0.1527972
 0.10916836 0.05309713 0.09688948 0.06139926 0.10084741 0.05034716
 0.10780726 0.15031673 0.14722863 0.14957318 0.15558857 0.15635289
 0.15637134 0.10481589 0.10654581 0.13051479 0.12659223 0.12525305
 0.12406856 0.09057076 0.12405393 0.13632219 0.1146832  0.12848526
 0.12624086 0.08836777 0.10690258 0.14410308 0.12366311 0.1311831
 0.111798   0.13054645 0.1399822  0.11113822 0.08618732 0.14611705
 0.06040096 0.149429   0.         0.18566415 0.1581849  0.12944318
 0.07967665 0.21056962 0.15607315 0.13851519 0.11921671 0.14493226
 0.11375856 0.1121859  0.20378095 0.13817059 0.12301282 0.09883215
 0.14875364 0.13400336 0.11910875 0.14841697 0.1280694  0.17970324
 0.06553056 0.10497924 0.13934903 0.12723337 0.10878649 0.17644277
 0.12477564 0.08322996 0.06948854 0.1009403  0.1135374  0.12066556
 0.13345866 0.15912724 0.11769099 0.13431218 0.14113921 0.09457822
 0.20110333 0.11344809 0.17722312 0.1381649  0.11485819 0.11910639
 0.1000935  0.1268384  0.12537704 0.1368081  0.05932555 0.14866954
 0.09055701 0.17627266 0.14850232 0.1038089  0.1130814  0.14259554
 0.15036589 0.13287403 0.12392177 0.19093406 0.08796145 0.10412295
 0.14192282 0.1078187  0.08456708 0.06056958 0.08041279 0.11070582
 0.13404274 0.0983322  0.1404881  0.14094946 0.12522665 0.05323122
 0.10778685 0.08140737 0.11656877 0.02525208 0.07044017 0.04866485
 0.11729054 0.17297539 0.14096178 0.14478612 0.17170544 0.12752178
 0.07531886 0.14201903 0.10162286 0.12731017 0.15158704 0.11413722
 0.16152577 0.19867192 0.14145029 0.12191311 0.10353033 0.15843849
 0.06889845 0.05882657 0.11764632 0.16066124 0.08054227 0.14803168
 0.11320507 0.16043624 0.19885123 0.16352957 0.10430237 0.03944552
 0.12891215 0.19222224 0.10915647 0.16742688 0.1128054  0.0835845
 0.14541706 0.11927255 0.16048537 0.09343883 0.17112927 0.09928641
 0.1167801  0.09792987 0.19039208 0.12440899 0.16284046 0.14539364
 0.16912754 0.15018898 0.16758655 0.0973464  0.08043073 0.12052716
 0.08441727 0.19371466 0.13100341 0.07061285 0.07313204 0.157463
 0.14123942 0.07273811 0.10707119 0.11807501 0.11573991 0.15309443
 0.15907729 0.14059034 0.14518553 0.13620016 0.13770421 0.1741237
 0.21988767 0.07053508 0.11674759 0.11569695 0.12723361 0.07696804
 0.07956757 0.13588813 0.08095998 0.12352368 0.1949324  0.1123224
 0.11896874 0.04049236 0.09173934 0.13102654 0.11672974 0.12126014
 0.08351004 0.12111515 0.17522544 0.14659077 0.08296033 0.1513844
 0.11659167 0.13962138 0.14408717 0.13425753 0.08852738 0.16009113
 0.2557649  0.15078692 0.08502984 0.08823878 0.1700638  0.10235827
 0.10530815 0.13351703 0.06881453 0.1172892  0.06808269 0.18704717
 0.22933735 0.13769613 0.17381623 0.09508312 0.18435706 0.11324972
 0.16299525 0.09266131 0.12375241 0.13678615 0.09963081 0.10127085
 0.15252998 0.11751616 0.15093419 0.10323996 0.14931267 0.11495364
 0.14399855 0.12605329 0.13041852 0.14378643 0.10442729 0.15744823
 0.14268498 0.15786862 0.16805764 0.12298524 0.07058505 0.11158643
 0.12723337 0.14604446 0.06310107 0.14268887 0.13383362 0.1724954
 0.13294062 0.12999474 0.13919947 0.09872483 0.16160148 0.14653651].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

All of our embeddings are no2w strictly positive. lets run the query now.

In [43]:


def query_sbert(query, top_k=5):
    print("Query: ", query)

    if not query:
        print("Empty query. Exiting.")
        return
    
    query_emb = encode_text_SBERT(query)

    similarities = []

    # Shifting the Embeddings
    query_emb = shift_embedding(query_emb)
    #psalm_SBERT_embeddings = shift_embedding(psalm_SBERT_embeddings)

    for i, psalm_emb in enumerate(psalm_SBERT_embeddings):
        #print(f"Query: {query_emb} \n Emedding: {psalm_emb}")
        sim = cosine_similarity(query_emb, psalm_emb)
        similarities.append((i, round(sim*100, 2)))

    
    # 3. Sort by similarity descending
    sims = sorted(similarities, reverse=True)[:5]
    

    # Return the top_k indices
    top_indices = [("SBERT", idx,sim) for idx, sim in sims[:top_k]]

    # Checking the Output
    return (top_indices)

query_sbert(query)

Query:  For the Peace of the World

ValueError: Expected 2D array, got 1D array instead:
array=[0.18852828 0.18038577 0.13007317 0.12583505 0.09035386 0.12300013
 0.1669517  0.11535031 0.15457655 0.19504657 0.17655672 0.0813558
 0.13699853 0.06883654 0.14890262 0.08516338 0.15521792 0.0934425
 0.15431707 0.14436063 0.10002033 0.17441243 0.11104466 0.13342108
 0.09946252 0.11249658 0.11631633 0.13754047 0.12242372 0.1397117
 0.08094171 0.06150312 0.1658932  0.0525072  0.1279224  0.12559523
 0.15212384 0.15874603 0.04698563 0.07424572 0.08499911 0.09808814
 0.09024425 0.09664926 0.13557315 0.16832171 0.14212206 0.08974532
 0.09700097 0.17219226 0.15252894 0.14817655 0.07107693 0.10421657
 0.07880723 0.11510949 0.12841427 0.07540093 0.1354664  0.18369359
 0.18811594 0.16924869 0.12029769 0.07962358 0.11895303 0.12250461
 0.15533546 0.16033415 0.17097458 0.10075626 0.11025392 0.10740429
 0.15649429 0.22672558 0.15471382 0.09112942 0.10015313 0.14369065
 0.15500566 0.16815539 0.21378213 0.14241399 0.13443626 0.12443306
 0.14318551 0.17274398 0.14041986 0.17019565 0.10105155 0.1351344
 0.02114183 0.06916191 0.12282457 0.12663576 0.07410942 0.07711761
 0.15760091 0.1389591  0.11042038 0.09149139 0.09570463 0.15711829
 0.19522727 0.15538026 0.12098171 0.1312352  0.16763169 0.12941794
 0.09646888 0.09453455 0.14652726 0.14164215 0.16011772 0.14808857
 0.08435199 0.12645178 0.15019697 0.18748054 0.14532928 0.15303366
 0.14305705 0.1294032  0.14815682 0.12017481 0.21400815 0.11983623
 0.08180054 0.1576187  0.08135648 0.16044386 0.08821292 0.1418839
 0.10238113 0.16148102 0.13502428 0.1865988  0.1389457  0.09659013
 0.1319412  0.10254565 0.15468445 0.13095632 0.1264825  0.17491572
 0.12924686 0.11469218 0.15499863 0.17365454 0.10631476 0.12087835
 0.17327465 0.11606237 0.13971812 0.15043443 0.13534069 0.1394405
 0.12943743 0.14485274 0.14031981 0.11624327 0.14876203 0.1189872
 0.0844219  0.1278596  0.06206493 0.14060374 0.18367931 0.15373535
 0.07184152 0.08861242 0.16507149 0.10212931 0.12523592 0.15693128
 0.12374561 0.14727907 0.12270754 0.08936702 0.0788112  0.12261292
 0.11340836 0.08039749 0.1366328  0.13953634 0.11439935 0.18785766
 0.14170757 0.14845535 0.12377983 0.19911157 0.14711818 0.12848638
 0.13477515 0.1628527  0.10593645 0.09899545 0.14052108 0.11321728
 0.15467782 0.04018254 0.14677341 0.09672014 0.11667974 0.09791704
 0.07523436 0.16184588 0.07947618 0.13390492 0.18173212 0.11584217
 0.1204915  0.13699153 0.13052046 0.15186027 0.10031469 0.10120191
 0.13449237 0.13661046 0.16093937 0.1812362  0.09089324 0.0708781
 0.09200953 0.11126652 0.20141736 0.11795837 0.0909159  0.15304986
 0.17067784 0.11721076 0.11341273 0.14364356 0.13717629 0.11817181
 0.18429396 0.07348235 0.16217707 0.16951054 0.18720627 0.
 0.1396301  0.16226748 0.11030279 0.13313109 0.11011354 0.1159292
 0.11738206 0.14430058 0.12562616 0.13775699 0.07408315 0.13978037
 0.10039072 0.15652795 0.08617339 0.13171881 0.13200538 0.19335559
 0.17802845 0.15581045 0.11684197 0.11758862 0.12263664 0.13827902
 0.18021108 0.11321083 0.15307274 0.08521301 0.12199923 0.0858414
 0.13618918 0.1273033  0.14778978 0.11404137 0.12742339 0.14061739
 0.14901692 0.09197223 0.08386573 0.12085979 0.10290191 0.08127092
 0.10763946 0.15359032 0.11541267 0.13117668 0.15148251 0.12647718
 0.12949565 0.11051983 0.09260753 0.14644198 0.11964307 0.03580118
 0.17566347 0.16751215 0.13262776 0.11601512 0.17908934 0.12313527
 0.1567932  0.12996443 0.13955419 0.14177954 0.08083649 0.12651584
 0.15613233 0.16000836 0.12759185 0.10863876 0.11339176 0.13446717
 0.12626609 0.07135624 0.12578024 0.12218955 0.07221906 0.05821025
 0.14056423 0.18203047 0.14650428 0.13100225 0.11307401 0.11976142
 0.14909141 0.17423502 0.18754013 0.13234101 0.1961228  0.09308445
 0.11930358 0.09976631 0.16849616 0.1313731  0.09326898 0.10107233
 0.08158594 0.06550041 0.04439398 0.14926341 0.12768863 0.08540253
 0.11821359 0.11222167 0.07350881 0.04762963 0.05980925 0.15330577
 0.13737679 0.14669822 0.22772002 0.11815163 0.13925752 0.13696112
 0.13938412 0.04765023 0.11495568 0.12558648 0.13435853 0.12634909
 0.08465067 0.12260666 0.1255086  0.16388945 0.1514722  0.1338611
 0.1955737  0.16032517 0.07618684 0.09491223 0.17667794 0.16376254
 0.15598458 0.19932705 0.07933614 0.1594835  0.14781325 0.10412789
 0.16965139 0.10847338 0.12893543 0.14059818 0.11460546 0.18106207
 0.06113032 0.08842173 0.15557018 0.11013314 0.10653057 0.12800263
 0.16163114 0.13670501 0.10954037 0.18670347 0.12685968 0.15098509
 0.15650837 0.15997203 0.12482487 0.1379585  0.15825035 0.21939781
 0.1238628  0.10431071 0.09342551 0.15099631 0.18345015 0.14098513
 0.21383715 0.07600029 0.13678016 0.18063933 0.11864997 0.18875125
 0.12636416 0.17070158 0.06459282 0.09800941 0.14786541 0.05140468
 0.10082179 0.14952262 0.09664489 0.12039218 0.15793276 0.14794731
 0.16311793 0.10911417 0.11219156 0.09944446 0.12540068 0.22136624
 0.11692209 0.0838997  0.06678952 0.12310711 0.12534532 0.12086323
 0.08564287 0.1597103  0.13396426 0.17944896 0.12290145 0.19045177
 0.08580337 0.14541811 0.1473029  0.15123273 0.12493376 0.10885944
 0.11844178 0.089912   0.11329424 0.1017479  0.1419223  0.15394008
 0.17615886 0.10332853 0.15781759 0.14233795 0.16045895 0.15302591
 0.13259068 0.16050687 0.14219125 0.15067816 0.13752101 0.0942236
 0.0891684  0.0883092  0.05727101 0.16462404 0.11422174 0.14853896
 0.09342533 0.1253572  0.10711795 0.18123588 0.09276225 0.14967151
 0.13656431 0.12315963 0.15205741 0.1650495  0.06819911 0.11200833
 0.15811472 0.15405606 0.14086471 0.18055555 0.10890867 0.1321945
 0.11895826 0.13128021 0.13897322 0.04082803 0.16680807 0.10002672
 0.11660789 0.10359275 0.16340305 0.12168309 0.13043638 0.18778943
 0.08821437 0.08730692 0.08038058 0.07779276 0.11191187 0.12013128
 0.20511144 0.14709124 0.06954549 0.01333831 0.15957342 0.12361021
 0.17465422 0.11252865 0.15945137 0.12131705 0.13013981 0.1400087
 0.15188578 0.12567104 0.15154967 0.09020667 0.09568103 0.11362325
 0.08975163 0.13768242 0.04221258 0.12784638 0.20037642 0.15248491
 0.10225631 0.1185623  0.09484562 0.196221   0.11963799 0.15182249
 0.14063625 0.14511782 0.11988329 0.1511008  0.09310902 0.14832309
 0.11540487 0.11661346 0.11626523 0.10130835 0.10282824 0.12224445
 0.05886834 0.11702172 0.16666391 0.12792082 0.18052737 0.16940363
 0.11618932 0.12699887 0.02994429 0.09247837 0.1302624  0.11781529
 0.05937219 0.14003864 0.08764185 0.12775587 0.13555434 0.12611274
 0.1815448  0.10397551 0.11742558 0.20095758 0.14161347 0.1299813
 0.15569432 0.08071962 0.15704985 0.18564187 0.13788475 0.13040859
 0.09100334 0.12615597 0.09447782 0.10807817 0.0997487  0.10152532
 0.12147152 0.11432274 0.13932434 0.1706944  0.12918925 0.13440199
 0.16482367 0.11154816 0.02984585 0.1323361  0.11216465 0.15284175
 0.11298679 0.08915096 0.09845199 0.16585937 0.1081565  0.12332179
 0.12537645 0.08861751 0.13193397 0.08780615 0.11200397 0.11353835
 0.11268216 0.12918979 0.12225912 0.16341896 0.11007347 0.16121902
 0.11683406 0.123192   0.09832873 0.12546709 0.0631282  0.12033189
 0.18517774 0.1199405  0.11745402 0.08990698 0.16351034 0.1918574
 0.11271224 0.05847739 0.05639881 0.19497818 0.0932217  0.16088523
 0.15672301 0.12660147 0.1977595  0.16786727 0.17410266 0.07598367
 0.11535915 0.21254617 0.13516542 0.10386057 0.09380251 0.12823188
 0.1472043  0.15692209 0.18726379 0.16396615 0.10089471 0.12850855
 0.1599134  0.06360058 0.18143487 0.12637657 0.08775719 0.09831186
 0.155881   0.14721951 0.10254622 0.14022803 0.12536947 0.10104275
 0.03992419 0.23045924 0.12226826 0.07902959 0.13024342 0.14755279
 0.11928868 0.07773481 0.13972467 0.03830317 0.10917789 0.19853815
 0.06910913 0.12864389 0.16291654 0.18175748 0.15816242 0.16430813
 0.08986624 0.08469157 0.08414215 0.09973235 0.12792103 0.0867224
 0.11881047 0.1577416  0.15668535 0.07901123 0.16393849 0.09086344
 0.14961217 0.14171202 0.12567128 0.16145203 0.08670387 0.12940352
 0.11771367 0.11806819 0.10188173 0.14380848 0.06217039 0.12009273
 0.17246619 0.14386173 0.12570576 0.12597562 0.09515375 0.11516926
 0.14764842 0.1359649  0.03580397 0.14699925 0.14935803 0.18085395
 0.09844416 0.11281556 0.09225635 0.17161909 0.07157954 0.09710097
 0.16971008 0.18813044 0.13971089 0.05141462 0.07660975 0.13015078
 0.09128354 0.17878759 0.20710109 0.12662569 0.1259723  0.18073708
 0.18703583 0.06727025 0.14802657 0.11344071 0.14285862 0.14940095
 0.11878598 0.14416583 0.13928813 0.09657487 0.09366418 0.09550957
 0.19865869 0.10864095 0.21673706 0.13358782 0.16453332 0.12386849
 0.12792082 0.09429742 0.09463494 0.14830592 0.10395473 0.16826715
 0.16270101 0.05887289 0.10299149 0.12932393 0.11702594 0.11998879].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

With the embeddings a shfited, we are now getting really high similarities which could be a good thing. Lets now update the `cosine_similarity()` function to handle the shifting as all three algorithms are using this to compare and gather results. We are going to take the shifting out of the SBERT algorithm first.

In [44]:
def query_sbert(query, top_k=5):
    query_emb = encode_text_SBERT(query)

    similarities = []
    for i, psalm_emb in enumerate(psalm_SBERT_embeddings):
        sim = cosine_similarity(query_emb, psalm_emb)
        similarities.append((i, sim))  # store raw similarity (not scaled)

    # Sort by similarity descending
    sims = sorted(similarities, key=lambda x: x[1], reverse=True)[:top_k]

    # Return (method, index, similarity%) for top_k results
    top_indices = [("SBERT", idx, round(sim * 100, 2)) for idx, sim in sims]

    return top_indices

In [45]:
query_sbert("Have mercy on me, O God, have mercy on me. For my soul trusts in Thee, and in the shadow of Thy wings will I hope, until iniquity pass away.")

ValueError: Expected 2D array, got 1D array instead:
array=[ 2.30880603e-02  5.52229807e-02 -1.81517452e-02 -1.51621280e-02
 -1.20274173e-02  2.02007145e-02 -2.87168305e-02 -3.11766984e-03
 -2.69127414e-02  7.34464033e-03 -1.85080990e-02 -3.22566591e-02
  2.21964084e-02 -1.03941999e-01  4.37856168e-02 -2.86183041e-02
  1.51256733e-02  2.36431342e-02 -1.78380329e-02 -1.02117639e-02
  3.06228101e-02  3.40892971e-02  5.58028871e-04  2.87758075e-02
  1.51143270e-02 -1.84591077e-02  4.71405834e-02  4.00586016e-02
 -4.87335771e-02 -5.53386584e-02 -4.71250042e-02 -5.30657824e-03
  2.82146037e-02  1.16824945e-02  2.07015955e-06  9.79344547e-03
  4.44180742e-02 -2.19752006e-02 -4.70907129e-02 -1.46096926e-02
 -1.17477393e-02 -4.93772514e-02 -2.76191365e-02 -2.27809772e-02
  1.98179055e-02  8.25145096e-03 -2.34232266e-02  1.92610472e-02
 -4.31688242e-02  6.27384856e-02  9.66678746e-03  4.25523818e-02
 -2.33782250e-02 -1.97674185e-02  5.32848462e-02  1.85737591e-02
 -3.76516096e-02 -4.06214520e-02 -1.61315836e-02 -1.56442691e-02
  2.32344400e-03  4.16596346e-02 -4.10511857e-03 -9.85013787e-03
 -3.96663845e-02  9.63827968e-03  9.66888592e-02  3.41609269e-02
 -2.33629588e-02 -1.61072426e-02 -3.39020826e-02 -7.38178939e-03
  1.21186785e-02  6.38549626e-02 -2.55872874e-04  7.43355043e-03
 -7.07802782e-03 -3.75790298e-02  1.35807246e-02 -4.65191491e-02
 -1.05323056e-02  1.93112325e-02 -1.65984705e-02 -4.94837724e-02
 -2.76362933e-02 -9.03331675e-03  1.74506325e-02 -3.16185020e-02
  4.16637734e-02  1.99961578e-04 -1.11743741e-01 -7.18642864e-03
 -2.41198502e-02 -4.37470041e-02 -1.32205011e-02 -1.06157074e-02
 -2.23380588e-02 -2.29201019e-02 -1.23576839e-02 -2.46607102e-02
  7.80976787e-02 -1.79367382e-02 -2.42624991e-02  7.91190006e-03
 -1.75083950e-02 -5.76399006e-02  5.24401106e-03 -6.60136621e-03
 -6.12872932e-03  5.10043614e-02  3.07103954e-02  5.57735786e-02
  1.94080789e-02 -9.37881600e-03 -4.19246964e-02  2.65581477e-02
  1.06914388e-02  1.93440299e-02  4.41785045e-02  1.45315779e-02
  1.97238084e-02 -9.95740015e-03  2.54554264e-02 -1.42940246e-02
  1.59917474e-02 -7.45831951e-02  3.92857231e-02  6.78392267e-03
 -2.08305717e-02 -5.03571555e-02  1.78476721e-02  7.37057114e-03
 -4.02911231e-02 -4.85787727e-03 -2.27408744e-02  5.16338870e-02
 -1.03420392e-02 -3.65305343e-04  7.26983771e-02  4.35506664e-02
 -3.00956592e-02  1.31625235e-02  1.14561366e-02  4.36516665e-02
  3.65288369e-02  3.07964515e-02  1.02525847e-02 -2.08443664e-02
  1.06545573e-03  1.20164175e-02  3.02748978e-02  1.35877402e-03
  8.58987961e-03  2.13371757e-02 -5.03833778e-02 -3.32860239e-02
 -9.56370160e-02 -4.11563776e-02 -5.57372645e-02  5.59677975e-03
  3.31613831e-02 -8.15954711e-03  2.64649559e-02  3.64168286e-02
  1.13585163e-04  1.59795228e-02  1.57356970e-02  3.25538516e-02
 -6.92557693e-02 -6.21128343e-02 -1.47923436e-02 -2.20559891e-02
  1.88652636e-03 -3.30455638e-02  2.67566051e-02  6.04624078e-02
 -1.57819164e-03  2.40476280e-02 -2.69096699e-02  1.47406403e-02
 -1.60396774e-03 -8.01696852e-02 -3.97933871e-02 -1.41335977e-02
  9.37882289e-02  3.78566422e-02 -4.01937927e-04  2.75564194e-02
  1.41002499e-02  4.09552269e-02 -2.02241857e-02  2.40825433e-02
 -9.19071212e-02  2.47435085e-02 -2.27533281e-03 -4.67324583e-03
  2.82058003e-03 -3.00674438e-02  2.36613629e-03  1.07354391e-02
 -5.21166809e-03  7.71617517e-02  2.28893906e-02  3.50007042e-02
  1.08398171e-02  7.76032358e-02  4.00592349e-02  3.65366461e-03
  2.50241943e-02  2.32017972e-02 -4.62526977e-02  2.63751149e-02
 -8.69591255e-04  1.01112481e-02  5.90269268e-03  8.98950174e-02
  1.77018233e-02  4.56497334e-02 -8.80147144e-02  5.35023324e-02
 -2.34629679e-02 -3.76855675e-03 -2.60609742e-02 -8.67175870e-03
  9.76827219e-02 -7.83363008e-04 -3.20211686e-02 -2.56102392e-03
  6.04251698e-02 -1.27564101e-02 -2.19802018e-02 -1.85297802e-02
  3.74456793e-02  1.44792236e-02 -1.28978572e-03  2.47336905e-02
 -3.67525332e-02  2.07107868e-02  4.06478830e-02 -9.08443555e-02
  1.34568512e-02  4.59285127e-03 -8.64927005e-03 -1.45734113e-03
  1.65566001e-02 -7.11467788e-02  1.01360399e-02 -3.09036933e-02
  1.19032804e-02 -6.41134661e-03 -2.37541776e-02  4.31190953e-02
 -9.85678732e-02  5.96600026e-03 -5.01164515e-03 -5.20993695e-02
  2.36323066e-02  3.73865571e-03  9.76738483e-02 -7.68489838e-02
 -7.44912773e-02 -3.87954675e-02 -2.94057396e-03 -2.24800725e-02
 -4.89596277e-03  8.52130428e-02  5.30752167e-02 -4.31084968e-02
 -2.10768469e-02 -2.09138226e-02  5.33446623e-03  6.15221122e-03
  2.71582752e-02 -6.05984358e-03  9.29366983e-03 -2.22518202e-03
  2.60022841e-02  1.89244282e-02 -4.93805520e-02 -5.03100976e-02
 -3.29698771e-02 -2.27163695e-02  4.09968346e-02  2.99859047e-02
  3.21995392e-02 -2.52828631e-03  2.81137154e-02 -2.38178913e-02
  3.00609116e-02 -1.81736816e-02 -4.73414287e-02  1.03244772e-02
  1.33871883e-02 -4.69944961e-02 -8.19045119e-03  2.10848507e-02
 -8.89636278e-02 -4.45424803e-02  9.74003226e-03 -5.88487238e-02
 -3.03343292e-02  7.42900819e-02 -1.87251996e-02  6.58071786e-03
  2.31563225e-02 -6.67542890e-02  2.48337220e-02  1.67072862e-02
  5.32190781e-03 -2.54461896e-02  5.60119972e-02  3.34395561e-03
 -4.33427244e-02 -2.13950202e-02  1.88634843e-02  1.73172485e-02
  7.93370791e-03 -3.06822290e-03  2.56464873e-02 -4.68876474e-02
  4.17443886e-02 -2.93664597e-02  4.92687188e-02  3.30798002e-03
 -4.18216698e-02  2.33351383e-02  6.01968616e-02  6.37825057e-02
 -9.00437590e-04 -5.13667762e-02 -4.05417420e-02  3.33190337e-03
  1.51291750e-02  3.55119742e-02  3.60488743e-02 -3.83215323e-02
  4.68636602e-02  5.23196310e-02  4.53001820e-02  4.49072346e-02
  5.14442362e-02 -3.45981233e-02  2.46838871e-02  2.59477776e-02
 -9.03552994e-02 -5.89169487e-02  7.39421695e-02  3.31839770e-02
 -1.31551456e-02 -4.51388136e-02 -2.96237972e-02 -3.21461819e-02
  6.45001233e-03 -1.54790394e-02  1.99862402e-02 -6.48651719e-02
 -2.65673995e-02 -1.21551135e-03  3.27273086e-02  6.00708509e-03
  2.66741086e-02 -4.46911566e-02 -7.98776187e-03  6.15229309e-02
  2.74050180e-02  8.94089323e-03  2.40537450e-02  1.00370981e-02
  4.76986915e-02 -1.91099234e-02 -3.29549201e-02  4.93081138e-02
  3.11152507e-02  3.57656367e-02 -3.74257416e-02 -2.89665423e-02
  4.92677987e-02 -9.38206688e-02  2.95123775e-02 -2.94322055e-02
  3.29312123e-02 -6.31233230e-02 -2.89476980e-02 -1.90921538e-02
 -8.77266936e-03  1.08471513e-03  1.21503919e-02  3.78155336e-02
  3.03625520e-02 -2.69079078e-02 -5.73020987e-03  6.79929480e-02
  1.36848753e-02 -3.09976805e-02  3.50876637e-02 -3.38347116e-03
  3.66448350e-02  4.28292379e-02  2.05186903e-02  1.66904777e-02
  8.28802027e-03  9.89154875e-02  1.12761892e-02 -2.87728645e-02
  4.33382243e-02 -1.62359942e-02  6.02510665e-03 -4.26867567e-02
 -2.74910219e-02  1.08577928e-03 -2.86748577e-02  1.93371102e-02
  2.55815070e-02 -7.43796234e-04 -1.12697836e-02  3.33900824e-02
  2.98091181e-04 -7.08377212e-02 -4.54283180e-03 -8.42373073e-02
  1.08584063e-02  6.61628619e-02  2.74071097e-02  4.81902901e-03
 -4.65679186e-04  5.29876091e-02 -2.99165607e-03  7.08045159e-03
  4.79507484e-02  2.60548946e-03  9.82642081e-03  4.68288958e-02
 -3.29445042e-02 -4.75876965e-02 -7.06322417e-02 -3.94776464e-02
 -2.97943745e-02 -2.08218805e-02 -3.68708000e-02 -2.52687410e-02
  4.11442593e-02 -4.21777181e-03 -2.53886636e-02  4.84559219e-03
 -5.68233896e-03  3.18887793e-02 -1.08305393e-02 -4.74918187e-02
 -3.34994569e-02 -8.01596977e-03  1.74054001e-02 -6.01155534e-02
  2.45712269e-02  4.94758114e-02  3.55378874e-02 -2.67842710e-02
  6.26424253e-02 -2.98353191e-02  6.31085737e-03 -5.05140088e-02
  6.67931065e-02  5.94409602e-03 -1.20787707e-04 -1.14956740e-02
 -6.87102784e-06  8.27035233e-02 -7.08814785e-02 -6.35722578e-02
  4.33011688e-02 -2.34533125e-03 -6.44776151e-02  1.23839099e-02
 -1.82433445e-02  2.73516383e-02  1.05400831e-02  4.72737066e-02
 -2.65666712e-02  3.51759568e-02 -3.35200727e-02 -1.30758919e-02
 -2.18874775e-02 -6.81455657e-02  3.65291070e-03 -3.26755755e-02
  1.83269791e-02  2.24572327e-02  7.28934184e-02 -8.86928663e-03
  9.76762082e-03  5.43901697e-02  3.12956572e-02 -1.20511828e-02
  2.45390157e-03 -3.78297418e-02 -1.13698486e-02 -5.72779998e-02
 -1.14327781e-02 -4.99499217e-02  7.53169646e-04 -8.65069032e-03
  1.29718278e-02  2.44055875e-02  2.09285636e-02  2.67542861e-02
 -1.10985059e-02 -2.43001431e-02 -3.87771204e-02 -1.61393210e-02
  1.97967347e-02 -3.46586071e-02  7.80734606e-03 -4.47609043e-03
 -3.60670723e-02 -1.04970038e-01  2.32468415e-02 -6.56767190e-02
  1.34794880e-02  2.99380533e-02  1.92439202e-02  1.14679523e-02
  3.11026387e-02 -4.24066260e-02  7.35056913e-03 -8.92306853e-04
  5.68749532e-02 -3.88473757e-02 -3.25867385e-02  1.85258444e-02
  7.50681385e-03 -8.00967868e-03 -1.02107354e-01 -1.43807977e-02
  4.40413617e-02 -4.49085701e-03 -3.73134725e-02 -2.75733019e-03
 -1.46190794e-02  3.32131237e-02 -1.30873760e-02  3.01610716e-02
  1.21581787e-02  6.31122151e-04  6.57365546e-02 -1.21492036e-02
  1.74542163e-02 -4.27102298e-03 -1.74879562e-02  3.35002318e-02
 -1.10361893e-02 -1.06222080e-02  4.34418267e-04  7.46504217e-02
 -4.51172031e-02 -1.56881008e-02 -6.81267083e-02 -6.48492168e-33
  6.82878401e-03  2.03763954e-02 -4.35062125e-02  2.39407755e-02
 -5.80402091e-02 -6.37131976e-03  1.80904642e-02  1.28642097e-02
  2.14754492e-02  2.55304342e-03 -7.24231685e-03  2.63875052e-02
  5.25952782e-03  1.66158341e-02  8.58659819e-02 -2.83760694e-03
 -1.15489764e-02  2.33465377e-02  3.78072746e-02 -8.05785041e-03
 -2.42886916e-02  3.69445309e-02  4.54693213e-02 -1.14881046e-01
  2.10176073e-02 -3.29012633e-03 -3.05308010e-02 -1.85840055e-02
  3.15580852e-02  7.59641407e-03 -2.62383949e-02  5.10364585e-02
 -5.47546241e-03  1.87277328e-02 -9.10184253e-03  3.09942942e-02
  1.60761643e-02  6.83555845e-03  2.68457104e-02 -3.64319496e-02
  3.71669345e-02 -1.83860380e-02 -7.25105852e-02 -8.47103540e-03
 -4.48922440e-02 -1.63737815e-02  1.46029657e-02  2.90889684e-02
 -3.69489715e-02 -8.22666064e-02 -2.92991661e-02 -3.25875613e-03
 -2.02912241e-02 -1.32848769e-01 -4.55421954e-02 -8.01082002e-04
  6.49352977e-03  1.25345020e-02  1.44745674e-04  3.02243256e-03
 -8.41017067e-02  1.09028583e-02 -5.69792055e-02  8.88915174e-03
  1.84061136e-02  1.79136973e-02 -1.45340906e-02  9.95513052e-03
  2.81484704e-02  5.33346534e-02 -1.71440048e-03 -2.14692391e-02
  3.27771576e-03  6.70053530e-03 -4.15282026e-02 -2.15590708e-02
 -2.98279133e-02  2.08825376e-02  1.40114259e-02  1.22519983e-02
  4.54898700e-02 -6.36848388e-03  4.41533932e-03  1.24253174e-02
  3.58489752e-02 -1.15318917e-01  2.74078120e-02  3.06710806e-02
 -5.60492696e-03  1.18364645e-02 -1.71848349e-02  1.45611605e-02
  1.24239847e-02  2.72934996e-02 -3.54742147e-02 -3.43682393e-02
  4.73119318e-02  9.94381402e-03 -8.39659013e-03  4.62798681e-03
  3.92122157e-02 -2.68381741e-02 -1.51948817e-03  8.50765314e-03
  6.34357973e-04  4.76749521e-03  8.31903517e-02 -1.53153744e-02
 -3.68457958e-02  4.72938037e-03 -6.15031458e-03  5.33603784e-03
  1.00151356e-02  1.23783797e-02 -3.95299122e-03  5.12675419e-02
 -1.93208251e-02 -4.26233299e-02  4.29921830e-03 -7.76088238e-02
  3.54628190e-02  7.27484897e-02  4.38108249e-03  3.33678722e-02
 -5.52639365e-02 -2.31881440e-03 -1.62912626e-02 -2.34881863e-02
  2.49372870e-02 -2.74037588e-02 -2.06989869e-02 -1.30585274e-02
  2.77256760e-07  1.00584785e-02 -3.05247796e-03  2.59761252e-02
  1.16244750e-02  1.75898019e-02 -3.40020913e-03 -1.47551000e-02
  7.54798576e-03 -2.20460091e-02 -3.27290548e-03  2.37849560e-02
 -1.02289403e-02  2.09741984e-02 -6.03134334e-02 -2.32552607e-02
 -9.76846460e-03 -3.81556749e-02 -5.28651513e-02 -2.66239792e-02
  3.71718332e-02  2.41868198e-02  2.27585640e-02  2.32177172e-02
  6.59606792e-03  2.76815309e-03  4.36359458e-02  9.50934947e-04
 -9.16926116e-02  9.66722798e-03 -1.08452020e-02 -8.82916823e-02
  4.77547012e-02 -3.69029269e-02 -1.44655704e-02  1.97015759e-02
 -3.28425206e-02 -3.97671480e-03  6.44062907e-02 -4.61070891e-03
  1.45930909e-02 -1.95181854e-02 -2.16057040e-02 -2.42584869e-02
 -2.19668765e-02 -4.26612385e-02  3.30634750e-02  3.75624746e-02
  4.01519164e-02  3.08511779e-02  2.51555536e-02 -2.20849924e-02
  5.64552434e-02 -7.19131157e-02  1.17479442e-02  2.87181418e-02
  1.62021387e-02  3.93656157e-02 -5.79902390e-03  4.65973951e-02
  1.06225507e-02 -8.33153445e-03 -1.29892316e-03  4.83811414e-03
  2.93044373e-02  3.70045751e-02  1.75099995e-03 -1.32593401e-02
  1.56991231e-34  3.00489124e-02 -5.38875833e-02  4.30267081e-02
  7.49664158e-02 -1.43809943e-02  1.61902588e-02  1.96596682e-02
 -3.80535126e-02 -4.33552749e-02 -1.96414515e-02 -1.40862139e-02].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [ ]:
query_sbert("Have mercy on me, O God, have mercy on me. For my soul trusts in")

Then update the `cosine_similarity()` function.

In [ ]:
def cosine_similarity(a: np.ndarray, b: np.ndarray) -> float:
    ''' Ensuring that both embeddings are strictly positive'''
    if a.min() < 0:
        a = shift_embedding(a)
    
    if b.min() < 0:
        b = shift_embedding(b)
        
    """Compute cosine similarity between two 1D numpy arrays."""
    a_norm = a / np.linalg.norm(a)
    b_norm = b / np.linalg.norm(b)
    return float(np.dot(a_norm, b_norm))

Now lets examine of the results of all of the algorithms together.

# Testing All Algorithms

In [ ]:
def query_all(q):
    # GLoVe scaled by TF_IDF 
    (query_tfidf_glove(q))
    # BERT
    query_bert(q)
    # SBERT
    query_sbert(q)

print(query_all("For the Peace of the world"))

I want to be able to store ans keep track of the data generate by each of the three algorithms based on the queries. I want to store it all in a dataFrame for future analaysis

## Storing Algorithm

In [ ]:
full_results = pd.DataFrame(columns= ["Query", "Method", "Similarity Score (%)", "Text", "Psalm Num", "Verse"] )

In [ ]:
def record_results(query, results):
    for method, index, sim in results:
        target_psalm = psalms.iloc[index]

        full_results.loc[len(full_results)] = [
            query,
            method,
            sim,
            target_psalm["text"],
            target_psalm["psalm_num"],
            target_psalm["verse"]
        ]

In [ ]:
def query_all(q):
    # GLoVe scaled by TF_IDF 
    record_results(q, query_tfidf_glove(q))
    # BERT
    record_results(q, query_bert(q))
    # SBERT
    record_results(q, query_sbert(q))

query_all("Create in me a clean heart")

In [ ]:
query_all("prayer")

In [ ]:
full_results

# Graphing Results

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
plt.scatter(full_results['Psalm Num'], full_results["Similarity Score (%)"])

plt.show()

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
sns.scatterplot(
    data=full_results,
    x="Psalm Num",
    y="Similarity Score (%)",
    hue="Text",       # color by text
    size="Method",    # scale by method
    palette="viridis",
    sizes=(40, 200),
    alpha=0.8,
    edgecolor="k"
)

plt.title(f"Psalm Similarity by Text and Method \n Based on the Query: {query}")
#plt.suptitle(f"Based on the Query: {query}")

plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt
import textwrap

In [ ]:
# Defining a function for the graping
def graph_results(results):
    
    plt.figure(figsize=(10, 6))
    sns.scatterplot(
        data=results,
        x="Psalm Num",
        y="Similarity Score (%)",
        hue="Text",       # color by text
        size="Method",    # scale by method
        palette="viridis",
        sizes=(40, 200),
        alpha=0.8,
        edgecolor="k"
    )

    query = textwrap.fill(results.iloc[0]["Query"], width=60)

    plt.title(f"Psalm Similarity by Text and Method \n Based on the Query: {query}")
    #plt.suptitle(f"Based on the Query: {query}")

    plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
    plt.tight_layout()
    plt.show()

In [ ]:
# graph_results(full_results)

With everything needed to implents some investigations, lets work on runing a bunch of different queries to be able to look for any trends that may emerge. After a little thought and consulting ChatGPT I am going to use the following queries to test on all three of the algorithms. 
### Psalms Search Test Queries

#### 1. Simple Keyword Queries
- **Query 1:** mercy
- **Query 2** prayer - (applied towards the bottom)

#### 2. Phrase/Exact Match Queries
- **Query 3:** The Lord is my shepherd
- **Query 4:** Create in me a clean heart - (applied towards the bottom)

#### 3. Thematic/Semantic Queries
- **Query 5:** protection from enemies
- **Query 6:** praise in times of suffering

#### 4. Long/Complex Queries
- **Query 7:** How does the psalmist express trust in God while surrounded by fear and uncertaint?
- **Query 8:** Verses where the psalmist remembers past deliverance and uses it to find hope in present trials.

#### 5. Orthodox Service Quotes
##### From *Vespers*
- **Query 9:** 
    >"Rejoice, O ye heavens, sound the trumpets, ye foundation of the earth, thunder forth gladness, O ye mountains: for behold, Emanuel to    the Cross our sins, and the Giver of Life hath slain death, rasing up Adam,; for He loveth man kind."

- **Query 10:**
    >"“Have mercy on me, O God, have mercy on me. For my soul trusts in Thee, and in the shadow of Thy wings will I hope, until iniquity pass away.”

We can now store all of these within a dictionary to organize them.

In [ ]:
# psalm_queries.py (you can save this to import later)
queries = [
    # 1. Simple Keyword Queries
    {"id": 1, "category": "Simple Keyword", "text": "mercy"},

    # 2. Phrase/Exact Match Queries
    {"id": 2, "category": "Phrase/Exact Match", "text": "The Lord is my shepherd"},

    # 3. Thematic/Semantic Queries
    {"id": 3, "category": "Thematic/Semantic", "text": "protection from enemies"},
    {"id": 4, "category": "Thematic/Semantic", "text": "praise in times of suffering"},

    # 4. Long/Complex Queries
    {"id": 5, "category": "Long/Complex", 
     "text": "How does the psalmist express trust in God while surrounded by fear and uncertainty?"},
    {"id": 6, "category": "Long/Complex", 
     "text": "Verses where the psalmist remembers past deliverance and uses it to find hope in present trials."},

    # 5. Orthodox Service Quotes
    {"id": 7, "category": "Orthodox Service (Vespers)", 
     "text": "Rejoice, O ye heavens, sound the trumpets, ye foundation of the earth, thunder forth gladness, O ye mountains: for behold, Emmanuel to the Cross our sins, and the Giver of Life hath slain death, raising up Adam; for He loveth mankind."},

    {"id": 8, "category": "Orthodox Service: Great Canon of St. Andrew of Crete ", 
     "text": "Have mercy on me, O God, have mercy on me. For my soul trusts in Thee, and in the shadow of Thy wings will I hope, until iniquity pass away."}
]


queries

In [ ]:
for q in queries:
    query_all(q['text'])

In [ ]:
import pandas as pd

# Configure Pandas display options
pd.set_option('display.max_rows', 50)       # show all rows
pd.set_option('display.max_columns', None)    # show all columns
pd.set_option('display.max_colwidth', 180)   # don't truncate text
pd.set_option('display.expand_frame_repr', False)  # keep wide frames on one line

# Then simply display the DataFrame
full_results

In [ ]:
grouped_queries = full_results.groupby("Query")

grouped_queries

In [ ]:
for q, group in grouped_queries:
    graph_results(group)

In [ ]:
graph_results(full_results)

In [ ]:
query_all("Create in me a clean heart")

In [ ]:
query_all("incense")

In [ ]:
# full_results.to_csv("full_results.csv", index=False)

# TFIDF
After an intail set of scoring and seeing some results, it was decided it might be useful to just see `TF-IDF` as well.

In [ ]:
import os

BASE_DIR = os.getcwd()

In [ ]:
import os
import pickle
import pandas as pd

cwd = os.getcwd()

MODEL_PATH = os.path.abspath(
    os.path.join(
        cwd,
        "..",
        "data"
    )
)


with open(MODEL_PATH +"/psalms_tfidf_matrix.pickle", "rb") as f:
    tfidf_matrix = pickle.load(f)


with open(MODEL_PATH +"/psalms_tfidf_vectorizer.pickle", "rb") as f:
    tfidf_vectorizer = pickle.load(f)
with open(MODEL_PATH +"/grouped_psalm.csv", "rb") as f:
    psalms = pd.read_csv(f)

In [ ]:
psalms

In [ ]:
tfidf_vectorizer

In [ ]:
# tfidf_matrix

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

def query_tfidf(query, top_k=5):
    query_vec = tfidf_vectorizer.transform([query])

    sims = cosine_similarity(query_vec, tfidf_matrix).flatten()

    top_indices = sims.argsort()[::-1][:top_k]

    return pd.DataFrame({
        "Method": ["TF-IDF"] * len(top_indices),
        "Similarity Score (%)": sims[top_indices] * 100,
        "Text": psalms.iloc[top_indices]["text"].values,
        "Psalm Num": psalms.iloc[top_indices]["psalm_num"].values,
        "Verse": psalms.iloc[top_indices]["verse"].values
    })

In [ ]:
def record_results(query, results_df, results):
    """
    Append query results DataFrame to full_results.
    """
    for _, row in results_df.iterrows():
        # Extract values from the row
        method = row['Method']
        sim = row['Similarity Score (%)']
        text = row['Text']
        psalm_num = row['Psalm Num']
        verse = row['Verse']

        # Append to the global full_results DataFrame
        results.loc[len(results)] = [query, method, sim, text, psalm_num, verse]

In [ ]:
results = query_tfidf("for the peace of the world")
record_results("for the peace of the world", results)

In [ ]:
results = query_tfidf("Create in me a clean heart")
record_results("Create in me a clean heart", results)

In [ ]:
results = query_tfidf("prayer")
record_results("prayer", results)

In [ ]:
full_results

In [ ]:
full_results.to_csv("full_results.csv", mode="a", header=False, index=False)

In [ ]:

for q in queries:
    record_results(q['text'], query_tfidf(q['text']))
    
full_results

In [ ]:
# Adding the rest of the results to the undscored csv file
import os

output_file = "results.csv"

full_results.to_csv(
    output_file,
    mode="a",
    index=False,
    header=not os.path.exists(output_file)
)

# Collecting data for more queries

This section describes the creation of an expanded query set for evaluating a Psalms search engine. Since no standard benchmark exists for Psalms-specific retrieval, queries were manually designed to reflect common theological and semantic search intents within the text. They cover themes such as lament, repentance, praise, divine protection, human suffering, and God’s sovereignty. Queries were written in natural language to simulate realistic user information needs and were lightly paraphrased to increase linguistic diversity and improve evaluation robustness across different retrieval models.

In [ ]:
queries = pd.read_csv("queries.csv")

queries.head()

In [ ]:
queries['Query Category'].value_counts()

for i in range(len(queries['Query'])):
    #rint(queries['Query'][i])

In [ ]:
def query_all(q, df):
    # GLoVe scaled by TF_IDF 
    record_results(q, query_tfidf_glove(q), df)
    # BERT
    record_results(q, query_bert(q), df)
    # SBERT
    record_results(q, query_sbert(q), df)
    # TF_IDF
    record_results(q, query_tfidf(q), df)

In [ ]:
# New Dataframe for all of the previous and new queries
all_results = pd.DataFrame(columns= ["Query", "Method", "Similarity Score (%)", "Text", "Psalm Num", "Verse"] )

In [ ]:
for q in range(len(queries)):
    query_all(queries["Query"].iloc[q], all_results)

In [ ]:
all_results

In [ ]:
output_file = "all_results.csv"

all_results.to_csv(
    output_file,
    mode="a",
    index=False,
    header=not os.path.exists(output_file)
)